/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Connect.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace only {
    export class Connect extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            userId?: string;
            appId?: number;
            deviceKey?: string;
            roomId?: number;
            account?: string;
            prefix?: string;
            nickname?: string;
            host?: string;
            max?: number;
            deviceModel?: string;
            hosts?: string[];
            region?: string;
            phone?: string;
            email?: string;
            avatar?: string;
            getaway?: string;
            deviceName?: string;
            ip?: string;
            country?: string;
            city?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [11], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("deviceKey" in data && data.deviceKey != undefined) {
                    this.deviceKey = data.deviceKey;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("account" in data && data.account != undefined) {
                    this.account = data.account;
                }
                if ("prefix" in data && data.prefix != undefined) {
                    this.prefix = data.prefix;
                }
                if ("nickname" in data && data.nickname != undefined) {
                    this.nickname = data.nickname;
                }
                if ("host" in data && data.host != undefined) {
                    this.host = data.host;
                }
                if ("max" in data && data.max != undefined) {
                    this.max = data.max;
                }
                if ("deviceModel" in data && data.deviceModel != undefined) {
                    this.deviceModel = data.deviceModel;
                }
                if ("hosts" in data && data.hosts != undefined) {
                    this.hosts = data.hosts;
                }
                if ("region" in data && data.region != undefined) {
                    this.region = data.region;
                }
                if ("phone" in data && data.phone != undefined) {
                    this.phone = data.phone;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
                if ("getaway" in data && data.getaway != undefined) {
                    this.getaway = data.getaway;
                }
                if ("deviceName" in data && data.deviceName != undefined) {
                    this.deviceName = data.deviceName;
                }
                if ("ip" in data && data.ip != undefined) {
                    this.ip = data.ip;
                }
                if ("country" in data && data.country != undefined) {
                    this.country = data.country;
                }
                if ("city" in data && data.city != undefined) {
                    this.city = data.city;
                }
            }
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get deviceKey() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set deviceKey(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get account() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set account(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get prefix() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set prefix(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get nickname() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set nickname(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get host() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set host(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        get max() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set max(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get deviceModel() {
            return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
        }
        set deviceModel(value: string) {
            pb_1.Message.setField(this, 10, value);
        }
        get hosts() {
            return pb_1.Message.getFieldWithDefault(this, 11, []) as string[];
        }
        set hosts(value: string[]) {
            pb_1.Message.setField(this, 11, value);
        }
        get region() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set region(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get phone() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set phone(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get getaway() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set getaway(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get deviceName() {
            return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
        }
        set deviceName(value: string) {
            pb_1.Message.setField(this, 17, value);
        }
        get ip() {
            return pb_1.Message.getFieldWithDefault(this, 18, "") as string;
        }
        set ip(value: string) {
            pb_1.Message.setField(this, 18, value);
        }
        get country() {
            return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
        }
        set country(value: string) {
            pb_1.Message.setField(this, 19, value);
        }
        get city() {
            return pb_1.Message.getFieldWithDefault(this, 20, "") as string;
        }
        set city(value: string) {
            pb_1.Message.setField(this, 20, value);
        }
        static fromObject(data: {
            userId?: string;
            appId?: number;
            deviceKey?: string;
            roomId?: number;
            account?: string;
            prefix?: string;
            nickname?: string;
            host?: string;
            max?: number;
            deviceModel?: string;
            hosts?: string[];
            region?: string;
            phone?: string;
            email?: string;
            avatar?: string;
            getaway?: string;
            deviceName?: string;
            ip?: string;
            country?: string;
            city?: string;
        }): Connect {
            const message = new Connect({});
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.deviceKey != null) {
                message.deviceKey = data.deviceKey;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.account != null) {
                message.account = data.account;
            }
            if (data.prefix != null) {
                message.prefix = data.prefix;
            }
            if (data.nickname != null) {
                message.nickname = data.nickname;
            }
            if (data.host != null) {
                message.host = data.host;
            }
            if (data.max != null) {
                message.max = data.max;
            }
            if (data.deviceModel != null) {
                message.deviceModel = data.deviceModel;
            }
            if (data.hosts != null) {
                message.hosts = data.hosts;
            }
            if (data.region != null) {
                message.region = data.region;
            }
            if (data.phone != null) {
                message.phone = data.phone;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            if (data.getaway != null) {
                message.getaway = data.getaway;
            }
            if (data.deviceName != null) {
                message.deviceName = data.deviceName;
            }
            if (data.ip != null) {
                message.ip = data.ip;
            }
            if (data.country != null) {
                message.country = data.country;
            }
            if (data.city != null) {
                message.city = data.city;
            }
            return message;
        }
        toObject() {
            const data: {
                userId?: string;
                appId?: number;
                deviceKey?: string;
                roomId?: number;
                account?: string;
                prefix?: string;
                nickname?: string;
                host?: string;
                max?: number;
                deviceModel?: string;
                hosts?: string[];
                region?: string;
                phone?: string;
                email?: string;
                avatar?: string;
                getaway?: string;
                deviceName?: string;
                ip?: string;
                country?: string;
                city?: string;
            } = {};
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.deviceKey != null) {
                data.deviceKey = this.deviceKey;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.account != null) {
                data.account = this.account;
            }
            if (this.prefix != null) {
                data.prefix = this.prefix;
            }
            if (this.nickname != null) {
                data.nickname = this.nickname;
            }
            if (this.host != null) {
                data.host = this.host;
            }
            if (this.max != null) {
                data.max = this.max;
            }
            if (this.deviceModel != null) {
                data.deviceModel = this.deviceModel;
            }
            if (this.hosts != null) {
                data.hosts = this.hosts;
            }
            if (this.region != null) {
                data.region = this.region;
            }
            if (this.phone != null) {
                data.phone = this.phone;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            if (this.getaway != null) {
                data.getaway = this.getaway;
            }
            if (this.deviceName != null) {
                data.deviceName = this.deviceName;
            }
            if (this.ip != null) {
                data.ip = this.ip;
            }
            if (this.country != null) {
                data.country = this.country;
            }
            if (this.city != null) {
                data.city = this.city;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.userId.length)
                writer.writeString(1, this.userId);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.deviceKey.length)
                writer.writeString(3, this.deviceKey);
            if (this.roomId != 0)
                writer.writeInt64(4, this.roomId);
            if (this.account.length)
                writer.writeString(5, this.account);
            if (this.prefix.length)
                writer.writeString(6, this.prefix);
            if (this.nickname.length)
                writer.writeString(7, this.nickname);
            if (this.host.length)
                writer.writeString(8, this.host);
            if (this.max != 0)
                writer.writeInt32(9, this.max);
            if (this.deviceModel.length)
                writer.writeString(10, this.deviceModel);
            if (this.hosts.length)
                writer.writeRepeatedString(11, this.hosts);
            if (this.region.length)
                writer.writeString(12, this.region);
            if (this.phone.length)
                writer.writeString(13, this.phone);
            if (this.email.length)
                writer.writeString(14, this.email);
            if (this.avatar.length)
                writer.writeString(15, this.avatar);
            if (this.getaway.length)
                writer.writeString(16, this.getaway);
            if (this.deviceName.length)
                writer.writeString(17, this.deviceName);
            if (this.ip.length)
                writer.writeString(18, this.ip);
            if (this.country.length)
                writer.writeString(19, this.country);
            if (this.city.length)
                writer.writeString(20, this.city);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Connect {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Connect();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.userId = reader.readString();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.deviceKey = reader.readString();
                        break;
                    case 4:
                        message.roomId = reader.readInt64();
                        break;
                    case 5:
                        message.account = reader.readString();
                        break;
                    case 6:
                        message.prefix = reader.readString();
                        break;
                    case 7:
                        message.nickname = reader.readString();
                        break;
                    case 8:
                        message.host = reader.readString();
                        break;
                    case 9:
                        message.max = reader.readInt32();
                        break;
                    case 10:
                        message.deviceModel = reader.readString();
                        break;
                    case 11:
                        pb_1.Message.addToRepeatedField(message, 11, reader.readString());
                        break;
                    case 12:
                        message.region = reader.readString();
                        break;
                    case 13:
                        message.phone = reader.readString();
                        break;
                    case 14:
                        message.email = reader.readString();
                        break;
                    case 15:
                        message.avatar = reader.readString();
                        break;
                    case 16:
                        message.getaway = reader.readString();
                        break;
                    case 17:
                        message.deviceName = reader.readString();
                        break;
                    case 18:
                        message.ip = reader.readString();
                        break;
                    case 19:
                        message.country = reader.readString();
                        break;
                    case 20:
                        message.city = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Connect {
            return Connect.deserialize(bytes);
        }
    }
}
