/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Contacts.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as pb_1 from "google-protobuf";
export namespace only {
    export class Contacts extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.only.Meta;
            userId?: string;
            roomId?: number;
            fromRoomId?: number;
            nickname?: string;
            username?: string;
            avatar?: string;
            fromUserId?: string;
            subgroup?: string;
            account?: string;
            role?: string;
            lastTime?: string;
            talkMode?: number;
            muted?: number;
            apply?: number;
            upload?: number;
            downed?: number;
            black?: number;
            noise?: number;
            joinTeamId?: number;
            joinTime?: string;
            joinRoomId?: number;
            roomIds?: number[];
            userIds?: string[];
            teamIds?: number[];
            unique?: string;
            status?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8, 32, 33, 34], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("fromRoomId" in data && data.fromRoomId != undefined) {
                    this.fromRoomId = data.fromRoomId;
                }
                if ("nickname" in data && data.nickname != undefined) {
                    this.nickname = data.nickname;
                }
                if ("username" in data && data.username != undefined) {
                    this.username = data.username;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
                if ("fromUserId" in data && data.fromUserId != undefined) {
                    this.fromUserId = data.fromUserId;
                }
                if ("subgroup" in data && data.subgroup != undefined) {
                    this.subgroup = data.subgroup;
                }
                if ("account" in data && data.account != undefined) {
                    this.account = data.account;
                }
                if ("role" in data && data.role != undefined) {
                    this.role = data.role;
                }
                if ("lastTime" in data && data.lastTime != undefined) {
                    this.lastTime = data.lastTime;
                }
                if ("talkMode" in data && data.talkMode != undefined) {
                    this.talkMode = data.talkMode;
                }
                if ("muted" in data && data.muted != undefined) {
                    this.muted = data.muted;
                }
                if ("apply" in data && data.apply != undefined) {
                    this.apply = data.apply;
                }
                if ("upload" in data && data.upload != undefined) {
                    this.upload = data.upload;
                }
                if ("downed" in data && data.downed != undefined) {
                    this.downed = data.downed;
                }
                if ("black" in data && data.black != undefined) {
                    this.black = data.black;
                }
                if ("noise" in data && data.noise != undefined) {
                    this.noise = data.noise;
                }
                if ("joinTeamId" in data && data.joinTeamId != undefined) {
                    this.joinTeamId = data.joinTeamId;
                }
                if ("joinTime" in data && data.joinTime != undefined) {
                    this.joinTime = data.joinTime;
                }
                if ("joinRoomId" in data && data.joinRoomId != undefined) {
                    this.joinRoomId = data.joinRoomId;
                }
                if ("roomIds" in data && data.roomIds != undefined) {
                    this.roomIds = data.roomIds;
                }
                if ("userIds" in data && data.userIds != undefined) {
                    this.userIds = data.userIds;
                }
                if ("teamIds" in data && data.teamIds != undefined) {
                    this.teamIds = data.teamIds;
                }
                if ("unique" in data && data.unique != undefined) {
                    this.unique = data.unique;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.only.Meta, 10) as dependency_1.only.Meta;
        }
        set meta(value: dependency_1.only.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 12, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 12, value);
        }
        get fromRoomId() {
            return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
        }
        set fromRoomId(value: number) {
            pb_1.Message.setField(this, 13, value);
        }
        get nickname() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set nickname(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get username() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set username(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get fromUserId() {
            return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
        }
        set fromUserId(value: string) {
            pb_1.Message.setField(this, 17, value);
        }
        get subgroup() {
            return pb_1.Message.getFieldWithDefault(this, 18, "") as string;
        }
        set subgroup(value: string) {
            pb_1.Message.setField(this, 18, value);
        }
        get account() {
            return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
        }
        set account(value: string) {
            pb_1.Message.setField(this, 19, value);
        }
        get role() {
            return pb_1.Message.getFieldWithDefault(this, 20, "") as string;
        }
        set role(value: string) {
            pb_1.Message.setField(this, 20, value);
        }
        get lastTime() {
            return pb_1.Message.getFieldWithDefault(this, 21, "") as string;
        }
        set lastTime(value: string) {
            pb_1.Message.setField(this, 21, value);
        }
        get talkMode() {
            return pb_1.Message.getFieldWithDefault(this, 22, 0) as number;
        }
        set talkMode(value: number) {
            pb_1.Message.setField(this, 22, value);
        }
        get muted() {
            return pb_1.Message.getFieldWithDefault(this, 23, 0) as number;
        }
        set muted(value: number) {
            pb_1.Message.setField(this, 23, value);
        }
        get apply() {
            return pb_1.Message.getFieldWithDefault(this, 24, 0) as number;
        }
        set apply(value: number) {
            pb_1.Message.setField(this, 24, value);
        }
        get upload() {
            return pb_1.Message.getFieldWithDefault(this, 25, 0) as number;
        }
        set upload(value: number) {
            pb_1.Message.setField(this, 25, value);
        }
        get downed() {
            return pb_1.Message.getFieldWithDefault(this, 26, 0) as number;
        }
        set downed(value: number) {
            pb_1.Message.setField(this, 26, value);
        }
        get black() {
            return pb_1.Message.getFieldWithDefault(this, 27, 0) as number;
        }
        set black(value: number) {
            pb_1.Message.setField(this, 27, value);
        }
        get noise() {
            return pb_1.Message.getFieldWithDefault(this, 28, 0) as number;
        }
        set noise(value: number) {
            pb_1.Message.setField(this, 28, value);
        }
        get joinTeamId() {
            return pb_1.Message.getFieldWithDefault(this, 29, 0) as number;
        }
        set joinTeamId(value: number) {
            pb_1.Message.setField(this, 29, value);
        }
        get joinTime() {
            return pb_1.Message.getFieldWithDefault(this, 30, "") as string;
        }
        set joinTime(value: string) {
            pb_1.Message.setField(this, 30, value);
        }
        get joinRoomId() {
            return pb_1.Message.getFieldWithDefault(this, 31, 0) as number;
        }
        set joinRoomId(value: number) {
            pb_1.Message.setField(this, 31, value);
        }
        get roomIds() {
            return pb_1.Message.getFieldWithDefault(this, 32, []) as number[];
        }
        set roomIds(value: number[]) {
            pb_1.Message.setField(this, 32, value);
        }
        get userIds() {
            return pb_1.Message.getFieldWithDefault(this, 33, []) as string[];
        }
        set userIds(value: string[]) {
            pb_1.Message.setField(this, 33, value);
        }
        get teamIds() {
            return pb_1.Message.getFieldWithDefault(this, 34, []) as number[];
        }
        set teamIds(value: number[]) {
            pb_1.Message.setField(this, 34, value);
        }
        get unique() {
            return pb_1.Message.getFieldWithDefault(this, 36, "") as string;
        }
        set unique(value: string) {
            pb_1.Message.setField(this, 36, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 37, "") as string;
        }
        set status(value: string) {
            pb_1.Message.setField(this, 37, value);
        }
        static fromObject(data: {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
            userId?: string;
            roomId?: number;
            fromRoomId?: number;
            nickname?: string;
            username?: string;
            avatar?: string;
            fromUserId?: string;
            subgroup?: string;
            account?: string;
            role?: string;
            lastTime?: string;
            talkMode?: number;
            muted?: number;
            apply?: number;
            upload?: number;
            downed?: number;
            black?: number;
            noise?: number;
            joinTeamId?: number;
            joinTime?: string;
            joinRoomId?: number;
            roomIds?: number[];
            userIds?: string[];
            teamIds?: number[];
            unique?: string;
            status?: string;
        }): Contacts {
            const message = new Contacts({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.only.Meta.fromObject(data.meta);
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.fromRoomId != null) {
                message.fromRoomId = data.fromRoomId;
            }
            if (data.nickname != null) {
                message.nickname = data.nickname;
            }
            if (data.username != null) {
                message.username = data.username;
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            if (data.fromUserId != null) {
                message.fromUserId = data.fromUserId;
            }
            if (data.subgroup != null) {
                message.subgroup = data.subgroup;
            }
            if (data.account != null) {
                message.account = data.account;
            }
            if (data.role != null) {
                message.role = data.role;
            }
            if (data.lastTime != null) {
                message.lastTime = data.lastTime;
            }
            if (data.talkMode != null) {
                message.talkMode = data.talkMode;
            }
            if (data.muted != null) {
                message.muted = data.muted;
            }
            if (data.apply != null) {
                message.apply = data.apply;
            }
            if (data.upload != null) {
                message.upload = data.upload;
            }
            if (data.downed != null) {
                message.downed = data.downed;
            }
            if (data.black != null) {
                message.black = data.black;
            }
            if (data.noise != null) {
                message.noise = data.noise;
            }
            if (data.joinTeamId != null) {
                message.joinTeamId = data.joinTeamId;
            }
            if (data.joinTime != null) {
                message.joinTime = data.joinTime;
            }
            if (data.joinRoomId != null) {
                message.joinRoomId = data.joinRoomId;
            }
            if (data.roomIds != null) {
                message.roomIds = data.roomIds;
            }
            if (data.userIds != null) {
                message.userIds = data.userIds;
            }
            if (data.teamIds != null) {
                message.teamIds = data.teamIds;
            }
            if (data.unique != null) {
                message.unique = data.unique;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
                userId?: string;
                roomId?: number;
                fromRoomId?: number;
                nickname?: string;
                username?: string;
                avatar?: string;
                fromUserId?: string;
                subgroup?: string;
                account?: string;
                role?: string;
                lastTime?: string;
                talkMode?: number;
                muted?: number;
                apply?: number;
                upload?: number;
                downed?: number;
                black?: number;
                noise?: number;
                joinTeamId?: number;
                joinTime?: string;
                joinRoomId?: number;
                roomIds?: number[];
                userIds?: string[];
                teamIds?: number[];
                unique?: string;
                status?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.fromRoomId != null) {
                data.fromRoomId = this.fromRoomId;
            }
            if (this.nickname != null) {
                data.nickname = this.nickname;
            }
            if (this.username != null) {
                data.username = this.username;
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            if (this.fromUserId != null) {
                data.fromUserId = this.fromUserId;
            }
            if (this.subgroup != null) {
                data.subgroup = this.subgroup;
            }
            if (this.account != null) {
                data.account = this.account;
            }
            if (this.role != null) {
                data.role = this.role;
            }
            if (this.lastTime != null) {
                data.lastTime = this.lastTime;
            }
            if (this.talkMode != null) {
                data.talkMode = this.talkMode;
            }
            if (this.muted != null) {
                data.muted = this.muted;
            }
            if (this.apply != null) {
                data.apply = this.apply;
            }
            if (this.upload != null) {
                data.upload = this.upload;
            }
            if (this.downed != null) {
                data.downed = this.downed;
            }
            if (this.black != null) {
                data.black = this.black;
            }
            if (this.noise != null) {
                data.noise = this.noise;
            }
            if (this.joinTeamId != null) {
                data.joinTeamId = this.joinTeamId;
            }
            if (this.joinTime != null) {
                data.joinTime = this.joinTime;
            }
            if (this.joinRoomId != null) {
                data.joinRoomId = this.joinRoomId;
            }
            if (this.roomIds != null) {
                data.roomIds = this.roomIds;
            }
            if (this.userIds != null) {
                data.userIds = this.userIds;
            }
            if (this.teamIds != null) {
                data.teamIds = this.teamIds;
            }
            if (this.unique != null) {
                data.unique = this.unique;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.userId.length)
                writer.writeString(11, this.userId);
            if (this.roomId != 0)
                writer.writeInt64(12, this.roomId);
            if (this.fromRoomId != 0)
                writer.writeInt64(13, this.fromRoomId);
            if (this.nickname.length)
                writer.writeString(14, this.nickname);
            if (this.username.length)
                writer.writeString(15, this.username);
            if (this.avatar.length)
                writer.writeString(16, this.avatar);
            if (this.fromUserId.length)
                writer.writeString(17, this.fromUserId);
            if (this.subgroup.length)
                writer.writeString(18, this.subgroup);
            if (this.account.length)
                writer.writeString(19, this.account);
            if (this.role.length)
                writer.writeString(20, this.role);
            if (this.lastTime.length)
                writer.writeString(21, this.lastTime);
            if (this.talkMode != 0)
                writer.writeInt32(22, this.talkMode);
            if (this.muted != 0)
                writer.writeInt32(23, this.muted);
            if (this.apply != 0)
                writer.writeInt32(24, this.apply);
            if (this.upload != 0)
                writer.writeInt32(25, this.upload);
            if (this.downed != 0)
                writer.writeInt32(26, this.downed);
            if (this.black != 0)
                writer.writeInt32(27, this.black);
            if (this.noise != 0)
                writer.writeInt32(28, this.noise);
            if (this.joinTeamId != 0)
                writer.writeInt64(29, this.joinTeamId);
            if (this.joinTime.length)
                writer.writeString(30, this.joinTime);
            if (this.joinRoomId != 0)
                writer.writeInt64(31, this.joinRoomId);
            if (this.roomIds.length)
                writer.writePackedInt64(32, this.roomIds);
            if (this.userIds.length)
                writer.writeRepeatedString(33, this.userIds);
            if (this.teamIds.length)
                writer.writePackedInt64(34, this.teamIds);
            if (this.unique.length)
                writer.writeString(36, this.unique);
            if (this.status.length)
                writer.writeString(37, this.status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Contacts {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Contacts();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.only.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.userId = reader.readString();
                        break;
                    case 12:
                        message.roomId = reader.readInt64();
                        break;
                    case 13:
                        message.fromRoomId = reader.readInt64();
                        break;
                    case 14:
                        message.nickname = reader.readString();
                        break;
                    case 15:
                        message.username = reader.readString();
                        break;
                    case 16:
                        message.avatar = reader.readString();
                        break;
                    case 17:
                        message.fromUserId = reader.readString();
                        break;
                    case 18:
                        message.subgroup = reader.readString();
                        break;
                    case 19:
                        message.account = reader.readString();
                        break;
                    case 20:
                        message.role = reader.readString();
                        break;
                    case 21:
                        message.lastTime = reader.readString();
                        break;
                    case 22:
                        message.talkMode = reader.readInt32();
                        break;
                    case 23:
                        message.muted = reader.readInt32();
                        break;
                    case 24:
                        message.apply = reader.readInt32();
                        break;
                    case 25:
                        message.upload = reader.readInt32();
                        break;
                    case 26:
                        message.downed = reader.readInt32();
                        break;
                    case 27:
                        message.black = reader.readInt32();
                        break;
                    case 28:
                        message.noise = reader.readInt32();
                        break;
                    case 29:
                        message.joinTeamId = reader.readInt64();
                        break;
                    case 30:
                        message.joinTime = reader.readString();
                        break;
                    case 31:
                        message.joinRoomId = reader.readInt64();
                        break;
                    case 32:
                        message.roomIds = reader.readPackedInt64();
                        break;
                    case 33:
                        pb_1.Message.addToRepeatedField(message, 33, reader.readString());
                        break;
                    case 34:
                        message.teamIds = reader.readPackedInt64();
                        break;
                    case 36:
                        message.unique = reader.readString();
                        break;
                    case 37:
                        message.status = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Contacts {
            return Contacts.deserialize(bytes);
        }
    }
}
