/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: ContactStatus.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as pb_1 from "google-protobuf";
export namespace onlyour.imio {
    export class ContactStatus extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            fromUserId?: string;
            fromRoomId?: number;
            remark?: string;
            meta?: dependency_1.onlyour.imio.Meta;
            userId?: string;
            device?: string;
            roomId?: number;
            status?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("fromUserId" in data && data.fromUserId != undefined) {
                    this.fromUserId = data.fromUserId;
                }
                if ("fromRoomId" in data && data.fromRoomId != undefined) {
                    this.fromRoomId = data.fromRoomId;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("device" in data && data.device != undefined) {
                    this.device = data.device;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get fromUserId() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set fromUserId(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get fromRoomId() {
            return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
        }
        set fromRoomId(value: number) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.onlyour.imio.Meta, 10) as dependency_1.onlyour.imio.Meta;
        }
        set meta(value: dependency_1.onlyour.imio.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get device() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set device(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 13, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set status(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        static fromObject(data: {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            fromUserId?: string;
            fromRoomId?: number;
            remark?: string;
            meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
            userId?: string;
            device?: string;
            roomId?: number;
            status?: string;
        }): ContactStatus {
            const message = new ContactStatus({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.fromUserId != null) {
                message.fromUserId = data.fromUserId;
            }
            if (data.fromRoomId != null) {
                message.fromRoomId = data.fromRoomId;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.onlyour.imio.Meta.fromObject(data.meta);
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.device != null) {
                message.device = data.device;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                fromUserId?: string;
                fromRoomId?: number;
                remark?: string;
                meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
                userId?: string;
                device?: string;
                roomId?: number;
                status?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.fromUserId != null) {
                data.fromUserId = this.fromUserId;
            }
            if (this.fromRoomId != null) {
                data.fromRoomId = this.fromRoomId;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.device != null) {
                data.device = this.device;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.fromUserId.length)
                writer.writeString(7, this.fromUserId);
            if (this.fromRoomId != 0)
                writer.writeInt64(8, this.fromRoomId);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.userId.length)
                writer.writeString(11, this.userId);
            if (this.device.length)
                writer.writeString(12, this.device);
            if (this.roomId != 0)
                writer.writeInt64(13, this.roomId);
            if (this.status.length)
                writer.writeString(14, this.status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ContactStatus {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ContactStatus();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        message.fromUserId = reader.readString();
                        break;
                    case 8:
                        message.fromRoomId = reader.readInt64();
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.onlyour.imio.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.userId = reader.readString();
                        break;
                    case 12:
                        message.device = reader.readString();
                        break;
                    case 13:
                        message.roomId = reader.readInt64();
                        break;
                    case 14:
                        message.status = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ContactStatus {
            return ContactStatus.deserialize(bytes);
        }
    }
}
