/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Gateway.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace onlyour.imio {
    export class Gateway extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            name?: string;
            host?: string;
            max?: number;
            remark?: string;
            ip?: number;
            one?: number;
            two?: number;
            three?: number;
            four?: number;
            five?: number;
            port?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("host" in data && data.host != undefined) {
                    this.host = data.host;
                }
                if ("max" in data && data.max != undefined) {
                    this.max = data.max;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("ip" in data && data.ip != undefined) {
                    this.ip = data.ip;
                }
                if ("one" in data && data.one != undefined) {
                    this.one = data.one;
                }
                if ("two" in data && data.two != undefined) {
                    this.two = data.two;
                }
                if ("three" in data && data.three != undefined) {
                    this.three = data.three;
                }
                if ("four" in data && data.four != undefined) {
                    this.four = data.four;
                }
                if ("five" in data && data.five != undefined) {
                    this.five = data.five;
                }
                if ("port" in data && data.port != undefined) {
                    this.port = data.port;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get host() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set host(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        get max() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set max(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 10, value);
        }
        get ip() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set ip(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get one() {
            return pb_1.Message.getFieldWithDefault(this, 12, 0) as number;
        }
        set one(value: number) {
            pb_1.Message.setField(this, 12, value);
        }
        get two() {
            return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
        }
        set two(value: number) {
            pb_1.Message.setField(this, 13, value);
        }
        get three() {
            return pb_1.Message.getFieldWithDefault(this, 14, 0) as number;
        }
        set three(value: number) {
            pb_1.Message.setField(this, 14, value);
        }
        get four() {
            return pb_1.Message.getFieldWithDefault(this, 15, 0) as number;
        }
        set four(value: number) {
            pb_1.Message.setField(this, 15, value);
        }
        get five() {
            return pb_1.Message.getFieldWithDefault(this, 16, 0) as number;
        }
        set five(value: number) {
            pb_1.Message.setField(this, 16, value);
        }
        get port() {
            return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
        }
        set port(value: string) {
            pb_1.Message.setField(this, 17, value);
        }
        static fromObject(data: {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            name?: string;
            host?: string;
            max?: number;
            remark?: string;
            ip?: number;
            one?: number;
            two?: number;
            three?: number;
            four?: number;
            five?: number;
            port?: string;
        }): Gateway {
            const message = new Gateway({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.host != null) {
                message.host = data.host;
            }
            if (data.max != null) {
                message.max = data.max;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.ip != null) {
                message.ip = data.ip;
            }
            if (data.one != null) {
                message.one = data.one;
            }
            if (data.two != null) {
                message.two = data.two;
            }
            if (data.three != null) {
                message.three = data.three;
            }
            if (data.four != null) {
                message.four = data.four;
            }
            if (data.five != null) {
                message.five = data.five;
            }
            if (data.port != null) {
                message.port = data.port;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                name?: string;
                host?: string;
                max?: number;
                remark?: string;
                ip?: number;
                one?: number;
                two?: number;
                three?: number;
                four?: number;
                five?: number;
                port?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.host != null) {
                data.host = this.host;
            }
            if (this.max != null) {
                data.max = this.max;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.ip != null) {
                data.ip = this.ip;
            }
            if (this.one != null) {
                data.one = this.one;
            }
            if (this.two != null) {
                data.two = this.two;
            }
            if (this.three != null) {
                data.three = this.three;
            }
            if (this.four != null) {
                data.four = this.four;
            }
            if (this.five != null) {
                data.five = this.five;
            }
            if (this.port != null) {
                data.port = this.port;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.name.length)
                writer.writeString(7, this.name);
            if (this.host.length)
                writer.writeString(8, this.host);
            if (this.max != 0)
                writer.writeInt64(9, this.max);
            if (this.remark.length)
                writer.writeString(10, this.remark);
            if (this.ip != 0)
                writer.writeInt32(11, this.ip);
            if (this.one != 0)
                writer.writeInt32(12, this.one);
            if (this.two != 0)
                writer.writeInt32(13, this.two);
            if (this.three != 0)
                writer.writeInt32(14, this.three);
            if (this.four != 0)
                writer.writeInt32(15, this.four);
            if (this.five != 0)
                writer.writeInt64(16, this.five);
            if (this.port.length)
                writer.writeString(17, this.port);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Gateway {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Gateway();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        message.name = reader.readString();
                        break;
                    case 8:
                        message.host = reader.readString();
                        break;
                    case 9:
                        message.max = reader.readInt64();
                        break;
                    case 10:
                        message.remark = reader.readString();
                        break;
                    case 11:
                        message.ip = reader.readInt32();
                        break;
                    case 12:
                        message.one = reader.readInt32();
                        break;
                    case 13:
                        message.two = reader.readInt32();
                        break;
                    case 14:
                        message.three = reader.readInt32();
                        break;
                    case 15:
                        message.four = reader.readInt32();
                        break;
                    case 16:
                        message.five = reader.readInt64();
                        break;
                    case 17:
                        message.port = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Gateway {
            return Gateway.deserialize(bytes);
        }
    }
}
