/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: MessageSign.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as dependency_2 from "./Message";
import * as pb_1 from "google-protobuf";
export namespace onlyour.imio {
    export class MessageSign extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            messageId?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.onlyour.imio.Meta;
            roomId?: number;
            fromId?: string;
            fromName?: string;
            destId?: string;
            destName?: string;
            device?: string;
            level?: number;
            deviceKey?: string;
            message?: dependency_2.onlyour.imio.Message;
            sent?: string;
            succeed?: string;
            read?: string;
            revoke?: string;
            readBy?: number;
            deviceTag?: string;
            signId?: string;
            tag?: string;
            fromIds?: string[];
            destIds?: string[];
            end?: string;
            label?: string;
            destAccount?: string;
            fromAccount?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8, 29, 30], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("messageId" in data && data.messageId != undefined) {
                    this.messageId = data.messageId;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("fromId" in data && data.fromId != undefined) {
                    this.fromId = data.fromId;
                }
                if ("fromName" in data && data.fromName != undefined) {
                    this.fromName = data.fromName;
                }
                if ("destId" in data && data.destId != undefined) {
                    this.destId = data.destId;
                }
                if ("destName" in data && data.destName != undefined) {
                    this.destName = data.destName;
                }
                if ("device" in data && data.device != undefined) {
                    this.device = data.device;
                }
                if ("level" in data && data.level != undefined) {
                    this.level = data.level;
                }
                if ("deviceKey" in data && data.deviceKey != undefined) {
                    this.deviceKey = data.deviceKey;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
                if ("sent" in data && data.sent != undefined) {
                    this.sent = data.sent;
                }
                if ("succeed" in data && data.succeed != undefined) {
                    this.succeed = data.succeed;
                }
                if ("read" in data && data.read != undefined) {
                    this.read = data.read;
                }
                if ("revoke" in data && data.revoke != undefined) {
                    this.revoke = data.revoke;
                }
                if ("readBy" in data && data.readBy != undefined) {
                    this.readBy = data.readBy;
                }
                if ("deviceTag" in data && data.deviceTag != undefined) {
                    this.deviceTag = data.deviceTag;
                }
                if ("signId" in data && data.signId != undefined) {
                    this.signId = data.signId;
                }
                if ("tag" in data && data.tag != undefined) {
                    this.tag = data.tag;
                }
                if ("fromIds" in data && data.fromIds != undefined) {
                    this.fromIds = data.fromIds;
                }
                if ("destIds" in data && data.destIds != undefined) {
                    this.destIds = data.destIds;
                }
                if ("end" in data && data.end != undefined) {
                    this.end = data.end;
                }
                if ("label" in data && data.label != undefined) {
                    this.label = data.label;
                }
                if ("destAccount" in data && data.destAccount != undefined) {
                    this.destAccount = data.destAccount;
                }
                if ("fromAccount" in data && data.fromAccount != undefined) {
                    this.fromAccount = data.fromAccount;
                }
            }
        }
        get messageId() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set messageId(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.onlyour.imio.Meta, 10) as dependency_1.onlyour.imio.Meta;
        }
        set meta(value: dependency_1.onlyour.imio.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get fromId() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set fromId(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get fromName() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set fromName(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get destId() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set destId(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get destName() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set destName(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get device() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set device(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get level() {
            return pb_1.Message.getFieldWithDefault(this, 17, 0) as number;
        }
        set level(value: number) {
            pb_1.Message.setField(this, 17, value);
        }
        get deviceKey() {
            return pb_1.Message.getFieldWithDefault(this, 18, "") as string;
        }
        set deviceKey(value: string) {
            pb_1.Message.setField(this, 18, value);
        }
        get message() {
            return pb_1.Message.getWrapperField(this, dependency_2.onlyour.imio.Message, 19) as dependency_2.onlyour.imio.Message;
        }
        set message(value: dependency_2.onlyour.imio.Message) {
            pb_1.Message.setWrapperField(this, 19, value);
        }
        get has_message() {
            return pb_1.Message.getField(this, 19) != null;
        }
        get sent() {
            return pb_1.Message.getFieldWithDefault(this, 20, "") as string;
        }
        set sent(value: string) {
            pb_1.Message.setField(this, 20, value);
        }
        get succeed() {
            return pb_1.Message.getFieldWithDefault(this, 21, "") as string;
        }
        set succeed(value: string) {
            pb_1.Message.setField(this, 21, value);
        }
        get read() {
            return pb_1.Message.getFieldWithDefault(this, 22, "") as string;
        }
        set read(value: string) {
            pb_1.Message.setField(this, 22, value);
        }
        get revoke() {
            return pb_1.Message.getFieldWithDefault(this, 23, "") as string;
        }
        set revoke(value: string) {
            pb_1.Message.setField(this, 23, value);
        }
        get readBy() {
            return pb_1.Message.getFieldWithDefault(this, 24, 0) as number;
        }
        set readBy(value: number) {
            pb_1.Message.setField(this, 24, value);
        }
        get deviceTag() {
            return pb_1.Message.getFieldWithDefault(this, 25, "") as string;
        }
        set deviceTag(value: string) {
            pb_1.Message.setField(this, 25, value);
        }
        get signId() {
            return pb_1.Message.getFieldWithDefault(this, 27, "") as string;
        }
        set signId(value: string) {
            pb_1.Message.setField(this, 27, value);
        }
        get tag() {
            return pb_1.Message.getFieldWithDefault(this, 28, "") as string;
        }
        set tag(value: string) {
            pb_1.Message.setField(this, 28, value);
        }
        get fromIds() {
            return pb_1.Message.getFieldWithDefault(this, 29, []) as string[];
        }
        set fromIds(value: string[]) {
            pb_1.Message.setField(this, 29, value);
        }
        get destIds() {
            return pb_1.Message.getFieldWithDefault(this, 30, []) as string[];
        }
        set destIds(value: string[]) {
            pb_1.Message.setField(this, 30, value);
        }
        get end() {
            return pb_1.Message.getFieldWithDefault(this, 37, "") as string;
        }
        set end(value: string) {
            pb_1.Message.setField(this, 37, value);
        }
        get label() {
            return pb_1.Message.getFieldWithDefault(this, 38, "") as string;
        }
        set label(value: string) {
            pb_1.Message.setField(this, 38, value);
        }
        get destAccount() {
            return pb_1.Message.getFieldWithDefault(this, 39, "") as string;
        }
        set destAccount(value: string) {
            pb_1.Message.setField(this, 39, value);
        }
        get fromAccount() {
            return pb_1.Message.getFieldWithDefault(this, 40, "") as string;
        }
        set fromAccount(value: string) {
            pb_1.Message.setField(this, 40, value);
        }
        static fromObject(data: {
            messageId?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
            roomId?: number;
            fromId?: string;
            fromName?: string;
            destId?: string;
            destName?: string;
            device?: string;
            level?: number;
            deviceKey?: string;
            message?: ReturnType<typeof dependency_2.onlyour.imio.Message.prototype.toObject>;
            sent?: string;
            succeed?: string;
            read?: string;
            revoke?: string;
            readBy?: number;
            deviceTag?: string;
            signId?: string;
            tag?: string;
            fromIds?: string[];
            destIds?: string[];
            end?: string;
            label?: string;
            destAccount?: string;
            fromAccount?: string;
        }): MessageSign {
            const message = new MessageSign({});
            if (data.messageId != null) {
                message.messageId = data.messageId;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.onlyour.imio.Meta.fromObject(data.meta);
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.fromId != null) {
                message.fromId = data.fromId;
            }
            if (data.fromName != null) {
                message.fromName = data.fromName;
            }
            if (data.destId != null) {
                message.destId = data.destId;
            }
            if (data.destName != null) {
                message.destName = data.destName;
            }
            if (data.device != null) {
                message.device = data.device;
            }
            if (data.level != null) {
                message.level = data.level;
            }
            if (data.deviceKey != null) {
                message.deviceKey = data.deviceKey;
            }
            if (data.message != null) {
                message.message = dependency_2.onlyour.imio.Message.fromObject(data.message);
            }
            if (data.sent != null) {
                message.sent = data.sent;
            }
            if (data.succeed != null) {
                message.succeed = data.succeed;
            }
            if (data.read != null) {
                message.read = data.read;
            }
            if (data.revoke != null) {
                message.revoke = data.revoke;
            }
            if (data.readBy != null) {
                message.readBy = data.readBy;
            }
            if (data.deviceTag != null) {
                message.deviceTag = data.deviceTag;
            }
            if (data.signId != null) {
                message.signId = data.signId;
            }
            if (data.tag != null) {
                message.tag = data.tag;
            }
            if (data.fromIds != null) {
                message.fromIds = data.fromIds;
            }
            if (data.destIds != null) {
                message.destIds = data.destIds;
            }
            if (data.end != null) {
                message.end = data.end;
            }
            if (data.label != null) {
                message.label = data.label;
            }
            if (data.destAccount != null) {
                message.destAccount = data.destAccount;
            }
            if (data.fromAccount != null) {
                message.fromAccount = data.fromAccount;
            }
            return message;
        }
        toObject() {
            const data: {
                messageId?: string;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
                roomId?: number;
                fromId?: string;
                fromName?: string;
                destId?: string;
                destName?: string;
                device?: string;
                level?: number;
                deviceKey?: string;
                message?: ReturnType<typeof dependency_2.onlyour.imio.Message.prototype.toObject>;
                sent?: string;
                succeed?: string;
                read?: string;
                revoke?: string;
                readBy?: number;
                deviceTag?: string;
                signId?: string;
                tag?: string;
                fromIds?: string[];
                destIds?: string[];
                end?: string;
                label?: string;
                destAccount?: string;
                fromAccount?: string;
            } = {};
            if (this.messageId != null) {
                data.messageId = this.messageId;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.fromId != null) {
                data.fromId = this.fromId;
            }
            if (this.fromName != null) {
                data.fromName = this.fromName;
            }
            if (this.destId != null) {
                data.destId = this.destId;
            }
            if (this.destName != null) {
                data.destName = this.destName;
            }
            if (this.device != null) {
                data.device = this.device;
            }
            if (this.level != null) {
                data.level = this.level;
            }
            if (this.deviceKey != null) {
                data.deviceKey = this.deviceKey;
            }
            if (this.message != null) {
                data.message = this.message.toObject();
            }
            if (this.sent != null) {
                data.sent = this.sent;
            }
            if (this.succeed != null) {
                data.succeed = this.succeed;
            }
            if (this.read != null) {
                data.read = this.read;
            }
            if (this.revoke != null) {
                data.revoke = this.revoke;
            }
            if (this.readBy != null) {
                data.readBy = this.readBy;
            }
            if (this.deviceTag != null) {
                data.deviceTag = this.deviceTag;
            }
            if (this.signId != null) {
                data.signId = this.signId;
            }
            if (this.tag != null) {
                data.tag = this.tag;
            }
            if (this.fromIds != null) {
                data.fromIds = this.fromIds;
            }
            if (this.destIds != null) {
                data.destIds = this.destIds;
            }
            if (this.end != null) {
                data.end = this.end;
            }
            if (this.label != null) {
                data.label = this.label;
            }
            if (this.destAccount != null) {
                data.destAccount = this.destAccount;
            }
            if (this.fromAccount != null) {
                data.fromAccount = this.fromAccount;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.messageId.length)
                writer.writeString(1, this.messageId);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.roomId != 0)
                writer.writeInt64(11, this.roomId);
            if (this.fromId.length)
                writer.writeString(12, this.fromId);
            if (this.fromName.length)
                writer.writeString(13, this.fromName);
            if (this.destId.length)
                writer.writeString(14, this.destId);
            if (this.destName.length)
                writer.writeString(15, this.destName);
            if (this.device.length)
                writer.writeString(16, this.device);
            if (this.level != 0)
                writer.writeInt32(17, this.level);
            if (this.deviceKey.length)
                writer.writeString(18, this.deviceKey);
            if (this.has_message)
                writer.writeMessage(19, this.message, () => this.message.serialize(writer));
            if (this.sent.length)
                writer.writeString(20, this.sent);
            if (this.succeed.length)
                writer.writeString(21, this.succeed);
            if (this.read.length)
                writer.writeString(22, this.read);
            if (this.revoke.length)
                writer.writeString(23, this.revoke);
            if (this.readBy != 0)
                writer.writeInt32(24, this.readBy);
            if (this.deviceTag.length)
                writer.writeString(25, this.deviceTag);
            if (this.signId.length)
                writer.writeString(27, this.signId);
            if (this.tag.length)
                writer.writeString(28, this.tag);
            if (this.fromIds.length)
                writer.writeRepeatedString(29, this.fromIds);
            if (this.destIds.length)
                writer.writeRepeatedString(30, this.destIds);
            if (this.end.length)
                writer.writeString(37, this.end);
            if (this.label.length)
                writer.writeString(38, this.label);
            if (this.destAccount.length)
                writer.writeString(39, this.destAccount);
            if (this.fromAccount.length)
                writer.writeString(40, this.fromAccount);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MessageSign {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MessageSign();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.messageId = reader.readString();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.onlyour.imio.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.roomId = reader.readInt64();
                        break;
                    case 12:
                        message.fromId = reader.readString();
                        break;
                    case 13:
                        message.fromName = reader.readString();
                        break;
                    case 14:
                        message.destId = reader.readString();
                        break;
                    case 15:
                        message.destName = reader.readString();
                        break;
                    case 16:
                        message.device = reader.readString();
                        break;
                    case 17:
                        message.level = reader.readInt32();
                        break;
                    case 18:
                        message.deviceKey = reader.readString();
                        break;
                    case 19:
                        reader.readMessage(message.message, () => message.message = dependency_2.onlyour.imio.Message.deserialize(reader));
                        break;
                    case 20:
                        message.sent = reader.readString();
                        break;
                    case 21:
                        message.succeed = reader.readString();
                        break;
                    case 22:
                        message.read = reader.readString();
                        break;
                    case 23:
                        message.revoke = reader.readString();
                        break;
                    case 24:
                        message.readBy = reader.readInt32();
                        break;
                    case 25:
                        message.deviceTag = reader.readString();
                        break;
                    case 27:
                        message.signId = reader.readString();
                        break;
                    case 28:
                        message.tag = reader.readString();
                        break;
                    case 29:
                        pb_1.Message.addToRepeatedField(message, 29, reader.readString());
                        break;
                    case 30:
                        pb_1.Message.addToRepeatedField(message, 30, reader.readString());
                        break;
                    case 37:
                        message.end = reader.readString();
                        break;
                    case 38:
                        message.label = reader.readString();
                        break;
                    case 39:
                        message.destAccount = reader.readString();
                        break;
                    case 40:
                        message.fromAccount = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MessageSign {
            return MessageSign.deserialize(bytes);
        }
    }
}
