/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Message.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as dependency_2 from "./MessageRemind";
import * as pb_1 from "google-protobuf";
export namespace only {
    export class Message extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            messageId?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            fromName?: string;
            meta?: dependency_1.only.Meta;
            roomId?: number;
            fromId?: string;
            destId?: string;
            mimeType?: string;
            subtype?: number;
            title?: string;
            subtitle?: string;
            cite?: string;
            text?: string;
            filename?: string;
            secret?: string;
            thumb?: string;
            url?: string;
            lat?: string;
            lng?: string;
            command?: string;
            size?: number;
            length?: number;
            sent?: string;
            host?: string;
            params?: string;
            citeData?: Message;
            cc?: dependency_2.only.MessageRemind[];
            destName?: string;
            talkMode?: number;
            tag?: string;
            deviceKey?: string;
            label?: string;
            remind?: dependency_2.only.MessageRemind[];
            fromAccount?: string;
            destAccount?: string;
            revoke?: string;
            deviceTag?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8, 33, 39], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("messageId" in data && data.messageId != undefined) {
                    this.messageId = data.messageId;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("fromName" in data && data.fromName != undefined) {
                    this.fromName = data.fromName;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("fromId" in data && data.fromId != undefined) {
                    this.fromId = data.fromId;
                }
                if ("destId" in data && data.destId != undefined) {
                    this.destId = data.destId;
                }
                if ("mimeType" in data && data.mimeType != undefined) {
                    this.mimeType = data.mimeType;
                }
                if ("subtype" in data && data.subtype != undefined) {
                    this.subtype = data.subtype;
                }
                if ("title" in data && data.title != undefined) {
                    this.title = data.title;
                }
                if ("subtitle" in data && data.subtitle != undefined) {
                    this.subtitle = data.subtitle;
                }
                if ("cite" in data && data.cite != undefined) {
                    this.cite = data.cite;
                }
                if ("text" in data && data.text != undefined) {
                    this.text = data.text;
                }
                if ("filename" in data && data.filename != undefined) {
                    this.filename = data.filename;
                }
                if ("secret" in data && data.secret != undefined) {
                    this.secret = data.secret;
                }
                if ("thumb" in data && data.thumb != undefined) {
                    this.thumb = data.thumb;
                }
                if ("url" in data && data.url != undefined) {
                    this.url = data.url;
                }
                if ("lat" in data && data.lat != undefined) {
                    this.lat = data.lat;
                }
                if ("lng" in data && data.lng != undefined) {
                    this.lng = data.lng;
                }
                if ("command" in data && data.command != undefined) {
                    this.command = data.command;
                }
                if ("size" in data && data.size != undefined) {
                    this.size = data.size;
                }
                if ("length" in data && data.length != undefined) {
                    this.length = data.length;
                }
                if ("sent" in data && data.sent != undefined) {
                    this.sent = data.sent;
                }
                if ("host" in data && data.host != undefined) {
                    this.host = data.host;
                }
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("citeData" in data && data.citeData != undefined) {
                    this.citeData = data.citeData;
                }
                if ("cc" in data && data.cc != undefined) {
                    this.cc = data.cc;
                }
                if ("destName" in data && data.destName != undefined) {
                    this.destName = data.destName;
                }
                if ("talkMode" in data && data.talkMode != undefined) {
                    this.talkMode = data.talkMode;
                }
                if ("tag" in data && data.tag != undefined) {
                    this.tag = data.tag;
                }
                if ("deviceKey" in data && data.deviceKey != undefined) {
                    this.deviceKey = data.deviceKey;
                }
                if ("label" in data && data.label != undefined) {
                    this.label = data.label;
                }
                if ("remind" in data && data.remind != undefined) {
                    this.remind = data.remind;
                }
                if ("fromAccount" in data && data.fromAccount != undefined) {
                    this.fromAccount = data.fromAccount;
                }
                if ("destAccount" in data && data.destAccount != undefined) {
                    this.destAccount = data.destAccount;
                }
                if ("revoke" in data && data.revoke != undefined) {
                    this.revoke = data.revoke;
                }
                if ("deviceTag" in data && data.deviceTag != undefined) {
                    this.deviceTag = data.deviceTag;
                }
            }
        }
        get messageId() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set messageId(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get fromName() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set fromName(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.only.Meta, 10) as dependency_1.only.Meta;
        }
        set meta(value: dependency_1.only.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get fromId() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set fromId(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get destId() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set destId(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get mimeType() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set mimeType(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get subtype() {
            return pb_1.Message.getFieldWithDefault(this, 15, 0) as number;
        }
        set subtype(value: number) {
            pb_1.Message.setField(this, 15, value);
        }
        get title() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set title(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get subtitle() {
            return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
        }
        set subtitle(value: string) {
            pb_1.Message.setField(this, 17, value);
        }
        get cite() {
            return pb_1.Message.getFieldWithDefault(this, 18, "") as string;
        }
        set cite(value: string) {
            pb_1.Message.setField(this, 18, value);
        }
        get text() {
            return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
        }
        set text(value: string) {
            pb_1.Message.setField(this, 19, value);
        }
        get filename() {
            return pb_1.Message.getFieldWithDefault(this, 20, "") as string;
        }
        set filename(value: string) {
            pb_1.Message.setField(this, 20, value);
        }
        get secret() {
            return pb_1.Message.getFieldWithDefault(this, 21, "") as string;
        }
        set secret(value: string) {
            pb_1.Message.setField(this, 21, value);
        }
        get thumb() {
            return pb_1.Message.getFieldWithDefault(this, 22, "") as string;
        }
        set thumb(value: string) {
            pb_1.Message.setField(this, 22, value);
        }
        get url() {
            return pb_1.Message.getFieldWithDefault(this, 23, "") as string;
        }
        set url(value: string) {
            pb_1.Message.setField(this, 23, value);
        }
        get lat() {
            return pb_1.Message.getFieldWithDefault(this, 24, "") as string;
        }
        set lat(value: string) {
            pb_1.Message.setField(this, 24, value);
        }
        get lng() {
            return pb_1.Message.getFieldWithDefault(this, 25, "") as string;
        }
        set lng(value: string) {
            pb_1.Message.setField(this, 25, value);
        }
        get command() {
            return pb_1.Message.getFieldWithDefault(this, 26, "") as string;
        }
        set command(value: string) {
            pb_1.Message.setField(this, 26, value);
        }
        get size() {
            return pb_1.Message.getFieldWithDefault(this, 27, 0) as number;
        }
        set size(value: number) {
            pb_1.Message.setField(this, 27, value);
        }
        get length() {
            return pb_1.Message.getFieldWithDefault(this, 28, 0) as number;
        }
        set length(value: number) {
            pb_1.Message.setField(this, 28, value);
        }
        get sent() {
            return pb_1.Message.getFieldWithDefault(this, 29, "") as string;
        }
        set sent(value: string) {
            pb_1.Message.setField(this, 29, value);
        }
        get host() {
            return pb_1.Message.getFieldWithDefault(this, 30, "") as string;
        }
        set host(value: string) {
            pb_1.Message.setField(this, 30, value);
        }
        get params() {
            return pb_1.Message.getFieldWithDefault(this, 31, "") as string;
        }
        set params(value: string) {
            pb_1.Message.setField(this, 31, value);
        }
        get citeData() {
            return pb_1.Message.getWrapperField(this, Message, 32) as Message;
        }
        set citeData(value: Message) {
            pb_1.Message.setWrapperField(this, 32, value);
        }
        get has_citeData() {
            return pb_1.Message.getField(this, 32) != null;
        }
        get cc() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_2.only.MessageRemind, 33) as dependency_2.only.MessageRemind[];
        }
        set cc(value: dependency_2.only.MessageRemind[]) {
            pb_1.Message.setRepeatedWrapperField(this, 33, value);
        }
        get destName() {
            return pb_1.Message.getFieldWithDefault(this, 34, "") as string;
        }
        set destName(value: string) {
            pb_1.Message.setField(this, 34, value);
        }
        get talkMode() {
            return pb_1.Message.getFieldWithDefault(this, 35, 0) as number;
        }
        set talkMode(value: number) {
            pb_1.Message.setField(this, 35, value);
        }
        get tag() {
            return pb_1.Message.getFieldWithDefault(this, 36, "") as string;
        }
        set tag(value: string) {
            pb_1.Message.setField(this, 36, value);
        }
        get deviceKey() {
            return pb_1.Message.getFieldWithDefault(this, 37, "") as string;
        }
        set deviceKey(value: string) {
            pb_1.Message.setField(this, 37, value);
        }
        get label() {
            return pb_1.Message.getFieldWithDefault(this, 38, "") as string;
        }
        set label(value: string) {
            pb_1.Message.setField(this, 38, value);
        }
        get remind() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_2.only.MessageRemind, 39) as dependency_2.only.MessageRemind[];
        }
        set remind(value: dependency_2.only.MessageRemind[]) {
            pb_1.Message.setRepeatedWrapperField(this, 39, value);
        }
        get fromAccount() {
            return pb_1.Message.getFieldWithDefault(this, 40, "") as string;
        }
        set fromAccount(value: string) {
            pb_1.Message.setField(this, 40, value);
        }
        get destAccount() {
            return pb_1.Message.getFieldWithDefault(this, 41, "") as string;
        }
        set destAccount(value: string) {
            pb_1.Message.setField(this, 41, value);
        }
        get revoke() {
            return pb_1.Message.getFieldWithDefault(this, 42, "") as string;
        }
        set revoke(value: string) {
            pb_1.Message.setField(this, 42, value);
        }
        get deviceTag() {
            return pb_1.Message.getFieldWithDefault(this, 43, "") as string;
        }
        set deviceTag(value: string) {
            pb_1.Message.setField(this, 43, value);
        }
        static fromObject(data: {
            messageId?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            fromName?: string;
            meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
            roomId?: number;
            fromId?: string;
            destId?: string;
            mimeType?: string;
            subtype?: number;
            title?: string;
            subtitle?: string;
            cite?: string;
            text?: string;
            filename?: string;
            secret?: string;
            thumb?: string;
            url?: string;
            lat?: string;
            lng?: string;
            command?: string;
            size?: number;
            length?: number;
            sent?: string;
            host?: string;
            params?: string;
            citeData?: ReturnType<typeof Message.prototype.toObject>;
            cc?: ReturnType<typeof dependency_2.only.MessageRemind.prototype.toObject>[];
            destName?: string;
            talkMode?: number;
            tag?: string;
            deviceKey?: string;
            label?: string;
            remind?: ReturnType<typeof dependency_2.only.MessageRemind.prototype.toObject>[];
            fromAccount?: string;
            destAccount?: string;
            revoke?: string;
            deviceTag?: string;
        }): Message {
            const message = new Message({});
            if (data.messageId != null) {
                message.messageId = data.messageId;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.fromName != null) {
                message.fromName = data.fromName;
            }
            if (data.meta != null) {
                message.meta = dependency_1.only.Meta.fromObject(data.meta);
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.fromId != null) {
                message.fromId = data.fromId;
            }
            if (data.destId != null) {
                message.destId = data.destId;
            }
            if (data.mimeType != null) {
                message.mimeType = data.mimeType;
            }
            if (data.subtype != null) {
                message.subtype = data.subtype;
            }
            if (data.title != null) {
                message.title = data.title;
            }
            if (data.subtitle != null) {
                message.subtitle = data.subtitle;
            }
            if (data.cite != null) {
                message.cite = data.cite;
            }
            if (data.text != null) {
                message.text = data.text;
            }
            if (data.filename != null) {
                message.filename = data.filename;
            }
            if (data.secret != null) {
                message.secret = data.secret;
            }
            if (data.thumb != null) {
                message.thumb = data.thumb;
            }
            if (data.url != null) {
                message.url = data.url;
            }
            if (data.lat != null) {
                message.lat = data.lat;
            }
            if (data.lng != null) {
                message.lng = data.lng;
            }
            if (data.command != null) {
                message.command = data.command;
            }
            if (data.size != null) {
                message.size = data.size;
            }
            if (data.length != null) {
                message.length = data.length;
            }
            if (data.sent != null) {
                message.sent = data.sent;
            }
            if (data.host != null) {
                message.host = data.host;
            }
            if (data.params != null) {
                message.params = data.params;
            }
            if (data.citeData != null) {
                message.citeData = Message.fromObject(data.citeData);
            }
            if (data.cc != null) {
                message.cc = data.cc.map(item => dependency_2.only.MessageRemind.fromObject(item));
            }
            if (data.destName != null) {
                message.destName = data.destName;
            }
            if (data.talkMode != null) {
                message.talkMode = data.talkMode;
            }
            if (data.tag != null) {
                message.tag = data.tag;
            }
            if (data.deviceKey != null) {
                message.deviceKey = data.deviceKey;
            }
            if (data.label != null) {
                message.label = data.label;
            }
            if (data.remind != null) {
                message.remind = data.remind.map(item => dependency_2.only.MessageRemind.fromObject(item));
            }
            if (data.fromAccount != null) {
                message.fromAccount = data.fromAccount;
            }
            if (data.destAccount != null) {
                message.destAccount = data.destAccount;
            }
            if (data.revoke != null) {
                message.revoke = data.revoke;
            }
            if (data.deviceTag != null) {
                message.deviceTag = data.deviceTag;
            }
            return message;
        }
        toObject() {
            const data: {
                messageId?: string;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                fromName?: string;
                meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
                roomId?: number;
                fromId?: string;
                destId?: string;
                mimeType?: string;
                subtype?: number;
                title?: string;
                subtitle?: string;
                cite?: string;
                text?: string;
                filename?: string;
                secret?: string;
                thumb?: string;
                url?: string;
                lat?: string;
                lng?: string;
                command?: string;
                size?: number;
                length?: number;
                sent?: string;
                host?: string;
                params?: string;
                citeData?: ReturnType<typeof Message.prototype.toObject>;
                cc?: ReturnType<typeof dependency_2.only.MessageRemind.prototype.toObject>[];
                destName?: string;
                talkMode?: number;
                tag?: string;
                deviceKey?: string;
                label?: string;
                remind?: ReturnType<typeof dependency_2.only.MessageRemind.prototype.toObject>[];
                fromAccount?: string;
                destAccount?: string;
                revoke?: string;
                deviceTag?: string;
            } = {};
            if (this.messageId != null) {
                data.messageId = this.messageId;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.fromName != null) {
                data.fromName = this.fromName;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.fromId != null) {
                data.fromId = this.fromId;
            }
            if (this.destId != null) {
                data.destId = this.destId;
            }
            if (this.mimeType != null) {
                data.mimeType = this.mimeType;
            }
            if (this.subtype != null) {
                data.subtype = this.subtype;
            }
            if (this.title != null) {
                data.title = this.title;
            }
            if (this.subtitle != null) {
                data.subtitle = this.subtitle;
            }
            if (this.cite != null) {
                data.cite = this.cite;
            }
            if (this.text != null) {
                data.text = this.text;
            }
            if (this.filename != null) {
                data.filename = this.filename;
            }
            if (this.secret != null) {
                data.secret = this.secret;
            }
            if (this.thumb != null) {
                data.thumb = this.thumb;
            }
            if (this.url != null) {
                data.url = this.url;
            }
            if (this.lat != null) {
                data.lat = this.lat;
            }
            if (this.lng != null) {
                data.lng = this.lng;
            }
            if (this.command != null) {
                data.command = this.command;
            }
            if (this.size != null) {
                data.size = this.size;
            }
            if (this.length != null) {
                data.length = this.length;
            }
            if (this.sent != null) {
                data.sent = this.sent;
            }
            if (this.host != null) {
                data.host = this.host;
            }
            if (this.params != null) {
                data.params = this.params;
            }
            if (this.citeData != null) {
                data.citeData = this.citeData.toObject();
            }
            if (this.cc != null) {
                data.cc = this.cc.map((item: dependency_2.only.MessageRemind) => item.toObject());
            }
            if (this.destName != null) {
                data.destName = this.destName;
            }
            if (this.talkMode != null) {
                data.talkMode = this.talkMode;
            }
            if (this.tag != null) {
                data.tag = this.tag;
            }
            if (this.deviceKey != null) {
                data.deviceKey = this.deviceKey;
            }
            if (this.label != null) {
                data.label = this.label;
            }
            if (this.remind != null) {
                data.remind = this.remind.map((item: dependency_2.only.MessageRemind) => item.toObject());
            }
            if (this.fromAccount != null) {
                data.fromAccount = this.fromAccount;
            }
            if (this.destAccount != null) {
                data.destAccount = this.destAccount;
            }
            if (this.revoke != null) {
                data.revoke = this.revoke;
            }
            if (this.deviceTag != null) {
                data.deviceTag = this.deviceTag;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.messageId.length)
                writer.writeString(1, this.messageId);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.fromName.length)
                writer.writeString(9, this.fromName);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.roomId != 0)
                writer.writeInt64(11, this.roomId);
            if (this.fromId.length)
                writer.writeString(12, this.fromId);
            if (this.destId.length)
                writer.writeString(13, this.destId);
            if (this.mimeType.length)
                writer.writeString(14, this.mimeType);
            if (this.subtype != 0)
                writer.writeInt32(15, this.subtype);
            if (this.title.length)
                writer.writeString(16, this.title);
            if (this.subtitle.length)
                writer.writeString(17, this.subtitle);
            if (this.cite.length)
                writer.writeString(18, this.cite);
            if (this.text.length)
                writer.writeString(19, this.text);
            if (this.filename.length)
                writer.writeString(20, this.filename);
            if (this.secret.length)
                writer.writeString(21, this.secret);
            if (this.thumb.length)
                writer.writeString(22, this.thumb);
            if (this.url.length)
                writer.writeString(23, this.url);
            if (this.lat.length)
                writer.writeString(24, this.lat);
            if (this.lng.length)
                writer.writeString(25, this.lng);
            if (this.command.length)
                writer.writeString(26, this.command);
            if (this.size != 0)
                writer.writeDouble(27, this.size);
            if (this.length != 0)
                writer.writeDouble(28, this.length);
            if (this.sent.length)
                writer.writeString(29, this.sent);
            if (this.host.length)
                writer.writeString(30, this.host);
            if (this.params.length)
                writer.writeString(31, this.params);
            if (this.has_citeData)
                writer.writeMessage(32, this.citeData, () => this.citeData.serialize(writer));
            if (this.cc.length)
                writer.writeRepeatedMessage(33, this.cc, (item: dependency_2.only.MessageRemind) => item.serialize(writer));
            if (this.destName.length)
                writer.writeString(34, this.destName);
            if (this.talkMode != 0)
                writer.writeInt32(35, this.talkMode);
            if (this.tag.length)
                writer.writeString(36, this.tag);
            if (this.deviceKey.length)
                writer.writeString(37, this.deviceKey);
            if (this.label.length)
                writer.writeString(38, this.label);
            if (this.remind.length)
                writer.writeRepeatedMessage(39, this.remind, (item: dependency_2.only.MessageRemind) => item.serialize(writer));
            if (this.fromAccount.length)
                writer.writeString(40, this.fromAccount);
            if (this.destAccount.length)
                writer.writeString(41, this.destAccount);
            if (this.revoke.length)
                writer.writeString(42, this.revoke);
            if (this.deviceTag.length)
                writer.writeString(43, this.deviceTag);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Message {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Message();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.messageId = reader.readString();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.fromName = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.only.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.roomId = reader.readInt64();
                        break;
                    case 12:
                        message.fromId = reader.readString();
                        break;
                    case 13:
                        message.destId = reader.readString();
                        break;
                    case 14:
                        message.mimeType = reader.readString();
                        break;
                    case 15:
                        message.subtype = reader.readInt32();
                        break;
                    case 16:
                        message.title = reader.readString();
                        break;
                    case 17:
                        message.subtitle = reader.readString();
                        break;
                    case 18:
                        message.cite = reader.readString();
                        break;
                    case 19:
                        message.text = reader.readString();
                        break;
                    case 20:
                        message.filename = reader.readString();
                        break;
                    case 21:
                        message.secret = reader.readString();
                        break;
                    case 22:
                        message.thumb = reader.readString();
                        break;
                    case 23:
                        message.url = reader.readString();
                        break;
                    case 24:
                        message.lat = reader.readString();
                        break;
                    case 25:
                        message.lng = reader.readString();
                        break;
                    case 26:
                        message.command = reader.readString();
                        break;
                    case 27:
                        message.size = reader.readDouble();
                        break;
                    case 28:
                        message.length = reader.readDouble();
                        break;
                    case 29:
                        message.sent = reader.readString();
                        break;
                    case 30:
                        message.host = reader.readString();
                        break;
                    case 31:
                        message.params = reader.readString();
                        break;
                    case 32:
                        reader.readMessage(message.citeData, () => message.citeData = Message.deserialize(reader));
                        break;
                    case 33:
                        reader.readMessage(message.cc, () => pb_1.Message.addToRepeatedWrapperField(message, 33, dependency_2.only.MessageRemind.deserialize(reader), dependency_2.only.MessageRemind));
                        break;
                    case 34:
                        message.destName = reader.readString();
                        break;
                    case 35:
                        message.talkMode = reader.readInt32();
                        break;
                    case 36:
                        message.tag = reader.readString();
                        break;
                    case 37:
                        message.deviceKey = reader.readString();
                        break;
                    case 38:
                        message.label = reader.readString();
                        break;
                    case 39:
                        reader.readMessage(message.remind, () => pb_1.Message.addToRepeatedWrapperField(message, 39, dependency_2.only.MessageRemind.deserialize(reader), dependency_2.only.MessageRemind));
                        break;
                    case 40:
                        message.fromAccount = reader.readString();
                        break;
                    case 41:
                        message.destAccount = reader.readString();
                        break;
                    case 42:
                        message.revoke = reader.readString();
                        break;
                    case 43:
                        message.deviceTag = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Message {
            return Message.deserialize(bytes);
        }
    }
}
