/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: MessageRemind.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as pb_1 from "google-protobuf";
export namespace onlyour.imio {
    export class MessageRemind extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.onlyour.imio.Meta;
            messageId?: string;
            destId?: string;
            fromId?: string;
            nickname?: string;
            confirm?: string;
            read?: string;
            roomId?: number;
            type?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("messageId" in data && data.messageId != undefined) {
                    this.messageId = data.messageId;
                }
                if ("destId" in data && data.destId != undefined) {
                    this.destId = data.destId;
                }
                if ("fromId" in data && data.fromId != undefined) {
                    this.fromId = data.fromId;
                }
                if ("nickname" in data && data.nickname != undefined) {
                    this.nickname = data.nickname;
                }
                if ("confirm" in data && data.confirm != undefined) {
                    this.confirm = data.confirm;
                }
                if ("read" in data && data.read != undefined) {
                    this.read = data.read;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.onlyour.imio.Meta, 10) as dependency_1.onlyour.imio.Meta;
        }
        set meta(value: dependency_1.onlyour.imio.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get messageId() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set messageId(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get destId() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set destId(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get fromId() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set fromId(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get nickname() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set nickname(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get confirm() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set confirm(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get read() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set read(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 17, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 17, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 18, 0) as number;
        }
        set type(value: number) {
            pb_1.Message.setField(this, 18, value);
        }
        static fromObject(data: {
            id?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
            messageId?: string;
            destId?: string;
            fromId?: string;
            nickname?: string;
            confirm?: string;
            read?: string;
            roomId?: number;
            type?: number;
        }): MessageRemind {
            const message = new MessageRemind({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.onlyour.imio.Meta.fromObject(data.meta);
            }
            if (data.messageId != null) {
                message.messageId = data.messageId;
            }
            if (data.destId != null) {
                message.destId = data.destId;
            }
            if (data.fromId != null) {
                message.fromId = data.fromId;
            }
            if (data.nickname != null) {
                message.nickname = data.nickname;
            }
            if (data.confirm != null) {
                message.confirm = data.confirm;
            }
            if (data.read != null) {
                message.read = data.read;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
                messageId?: string;
                destId?: string;
                fromId?: string;
                nickname?: string;
                confirm?: string;
                read?: string;
                roomId?: number;
                type?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.messageId != null) {
                data.messageId = this.messageId;
            }
            if (this.destId != null) {
                data.destId = this.destId;
            }
            if (this.fromId != null) {
                data.fromId = this.fromId;
            }
            if (this.nickname != null) {
                data.nickname = this.nickname;
            }
            if (this.confirm != null) {
                data.confirm = this.confirm;
            }
            if (this.read != null) {
                data.read = this.read;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.messageId.length)
                writer.writeString(11, this.messageId);
            if (this.destId.length)
                writer.writeString(12, this.destId);
            if (this.fromId.length)
                writer.writeString(13, this.fromId);
            if (this.nickname.length)
                writer.writeString(14, this.nickname);
            if (this.confirm.length)
                writer.writeString(15, this.confirm);
            if (this.read.length)
                writer.writeString(16, this.read);
            if (this.roomId != 0)
                writer.writeInt64(17, this.roomId);
            if (this.type != 0)
                writer.writeInt32(18, this.type);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MessageRemind {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MessageRemind();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.onlyour.imio.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.messageId = reader.readString();
                        break;
                    case 12:
                        message.destId = reader.readString();
                        break;
                    case 13:
                        message.fromId = reader.readString();
                        break;
                    case 14:
                        message.nickname = reader.readString();
                        break;
                    case 15:
                        message.confirm = reader.readString();
                        break;
                    case 16:
                        message.read = reader.readString();
                        break;
                    case 17:
                        message.roomId = reader.readInt64();
                        break;
                    case 18:
                        message.type = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MessageRemind {
            return MessageRemind.deserialize(bytes);
        }
    }
}
