/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Meta.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace only {
    export class Meta extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            deviceKey?: string;
            appId?: number;
            userId?: string;
            roomId?: number;
            teamId?: number;
            startTime?: string;
            endTime?: string;
            ids?: string[];
            token?: string;
            roomIds?: number[];
            userIds?: string[];
            teamIds?: number[];
            keys?: number[];
            page?: number;
            pageSize?: number;
            version?: string;
            v?: number;
            talkMode?: number;
            proto?: string;
            nickname?: string;
            protocol?: Uint8Array;
            deviceTag?: string;
            avatar?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [8, 10, 11, 12, 13], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("deviceKey" in data && data.deviceKey != undefined) {
                    this.deviceKey = data.deviceKey;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("teamId" in data && data.teamId != undefined) {
                    this.teamId = data.teamId;
                }
                if ("startTime" in data && data.startTime != undefined) {
                    this.startTime = data.startTime;
                }
                if ("endTime" in data && data.endTime != undefined) {
                    this.endTime = data.endTime;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("token" in data && data.token != undefined) {
                    this.token = data.token;
                }
                if ("roomIds" in data && data.roomIds != undefined) {
                    this.roomIds = data.roomIds;
                }
                if ("userIds" in data && data.userIds != undefined) {
                    this.userIds = data.userIds;
                }
                if ("teamIds" in data && data.teamIds != undefined) {
                    this.teamIds = data.teamIds;
                }
                if ("keys" in data && data.keys != undefined) {
                    this.keys = data.keys;
                }
                if ("page" in data && data.page != undefined) {
                    this.page = data.page;
                }
                if ("pageSize" in data && data.pageSize != undefined) {
                    this.pageSize = data.pageSize;
                }
                if ("version" in data && data.version != undefined) {
                    this.version = data.version;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("talkMode" in data && data.talkMode != undefined) {
                    this.talkMode = data.talkMode;
                }
                if ("proto" in data && data.proto != undefined) {
                    this.proto = data.proto;
                }
                if ("nickname" in data && data.nickname != undefined) {
                    this.nickname = data.nickname;
                }
                if ("protocol" in data && data.protocol != undefined) {
                    this.protocol = data.protocol;
                }
                if ("deviceTag" in data && data.deviceTag != undefined) {
                    this.deviceTag = data.deviceTag;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
            }
        }
        get deviceKey() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set deviceKey(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get teamId() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set teamId(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get startTime() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set startTime(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get endTime() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set endTime(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get token() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set token(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get roomIds() {
            return pb_1.Message.getFieldWithDefault(this, 10, []) as number[];
        }
        set roomIds(value: number[]) {
            pb_1.Message.setField(this, 10, value);
        }
        get userIds() {
            return pb_1.Message.getFieldWithDefault(this, 11, []) as string[];
        }
        set userIds(value: string[]) {
            pb_1.Message.setField(this, 11, value);
        }
        get teamIds() {
            return pb_1.Message.getFieldWithDefault(this, 12, []) as number[];
        }
        set teamIds(value: number[]) {
            pb_1.Message.setField(this, 12, value);
        }
        get keys() {
            return pb_1.Message.getFieldWithDefault(this, 13, []) as number[];
        }
        set keys(value: number[]) {
            pb_1.Message.setField(this, 13, value);
        }
        get page() {
            return pb_1.Message.getFieldWithDefault(this, 14, 0) as number;
        }
        set page(value: number) {
            pb_1.Message.setField(this, 14, value);
        }
        get pageSize() {
            return pb_1.Message.getFieldWithDefault(this, 15, 0) as number;
        }
        set pageSize(value: number) {
            pb_1.Message.setField(this, 15, value);
        }
        get version() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set version(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 17, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 17, value);
        }
        get talkMode() {
            return pb_1.Message.getFieldWithDefault(this, 18, 0) as number;
        }
        set talkMode(value: number) {
            pb_1.Message.setField(this, 18, value);
        }
        get proto() {
            return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
        }
        set proto(value: string) {
            pb_1.Message.setField(this, 19, value);
        }
        get nickname() {
            return pb_1.Message.getFieldWithDefault(this, 20, "") as string;
        }
        set nickname(value: string) {
            pb_1.Message.setField(this, 20, value);
        }
        get protocol() {
            return pb_1.Message.getFieldWithDefault(this, 21, new Uint8Array(0)) as Uint8Array;
        }
        set protocol(value: Uint8Array) {
            pb_1.Message.setField(this, 21, value);
        }
        get deviceTag() {
            return pb_1.Message.getFieldWithDefault(this, 22, "") as string;
        }
        set deviceTag(value: string) {
            pb_1.Message.setField(this, 22, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 23, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 23, value);
        }
        static fromObject(data: {
            deviceKey?: string;
            appId?: number;
            userId?: string;
            roomId?: number;
            teamId?: number;
            startTime?: string;
            endTime?: string;
            ids?: string[];
            token?: string;
            roomIds?: number[];
            userIds?: string[];
            teamIds?: number[];
            keys?: number[];
            page?: number;
            pageSize?: number;
            version?: string;
            v?: number;
            talkMode?: number;
            proto?: string;
            nickname?: string;
            protocol?: Uint8Array;
            deviceTag?: string;
            avatar?: string;
        }): Meta {
            const message = new Meta({});
            if (data.deviceKey != null) {
                message.deviceKey = data.deviceKey;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.teamId != null) {
                message.teamId = data.teamId;
            }
            if (data.startTime != null) {
                message.startTime = data.startTime;
            }
            if (data.endTime != null) {
                message.endTime = data.endTime;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.token != null) {
                message.token = data.token;
            }
            if (data.roomIds != null) {
                message.roomIds = data.roomIds;
            }
            if (data.userIds != null) {
                message.userIds = data.userIds;
            }
            if (data.teamIds != null) {
                message.teamIds = data.teamIds;
            }
            if (data.keys != null) {
                message.keys = data.keys;
            }
            if (data.page != null) {
                message.page = data.page;
            }
            if (data.pageSize != null) {
                message.pageSize = data.pageSize;
            }
            if (data.version != null) {
                message.version = data.version;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.talkMode != null) {
                message.talkMode = data.talkMode;
            }
            if (data.proto != null) {
                message.proto = data.proto;
            }
            if (data.nickname != null) {
                message.nickname = data.nickname;
            }
            if (data.protocol != null) {
                message.protocol = data.protocol;
            }
            if (data.deviceTag != null) {
                message.deviceTag = data.deviceTag;
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            return message;
        }
        toObject() {
            const data: {
                deviceKey?: string;
                appId?: number;
                userId?: string;
                roomId?: number;
                teamId?: number;
                startTime?: string;
                endTime?: string;
                ids?: string[];
                token?: string;
                roomIds?: number[];
                userIds?: string[];
                teamIds?: number[];
                keys?: number[];
                page?: number;
                pageSize?: number;
                version?: string;
                v?: number;
                talkMode?: number;
                proto?: string;
                nickname?: string;
                protocol?: Uint8Array;
                deviceTag?: string;
                avatar?: string;
            } = {};
            if (this.deviceKey != null) {
                data.deviceKey = this.deviceKey;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.teamId != null) {
                data.teamId = this.teamId;
            }
            if (this.startTime != null) {
                data.startTime = this.startTime;
            }
            if (this.endTime != null) {
                data.endTime = this.endTime;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.token != null) {
                data.token = this.token;
            }
            if (this.roomIds != null) {
                data.roomIds = this.roomIds;
            }
            if (this.userIds != null) {
                data.userIds = this.userIds;
            }
            if (this.teamIds != null) {
                data.teamIds = this.teamIds;
            }
            if (this.keys != null) {
                data.keys = this.keys;
            }
            if (this.page != null) {
                data.page = this.page;
            }
            if (this.pageSize != null) {
                data.pageSize = this.pageSize;
            }
            if (this.version != null) {
                data.version = this.version;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.talkMode != null) {
                data.talkMode = this.talkMode;
            }
            if (this.proto != null) {
                data.proto = this.proto;
            }
            if (this.nickname != null) {
                data.nickname = this.nickname;
            }
            if (this.protocol != null) {
                data.protocol = this.protocol;
            }
            if (this.deviceTag != null) {
                data.deviceTag = this.deviceTag;
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.deviceKey.length)
                writer.writeString(1, this.deviceKey);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.userId.length)
                writer.writeString(3, this.userId);
            if (this.roomId != 0)
                writer.writeInt64(4, this.roomId);
            if (this.teamId != 0)
                writer.writeInt64(5, this.teamId);
            if (this.startTime.length)
                writer.writeString(6, this.startTime);
            if (this.endTime.length)
                writer.writeString(7, this.endTime);
            if (this.ids.length)
                writer.writeRepeatedString(8, this.ids);
            if (this.token.length)
                writer.writeString(9, this.token);
            if (this.roomIds.length)
                writer.writePackedInt64(10, this.roomIds);
            if (this.userIds.length)
                writer.writeRepeatedString(11, this.userIds);
            if (this.teamIds.length)
                writer.writePackedInt64(12, this.teamIds);
            if (this.keys.length)
                writer.writePackedInt64(13, this.keys);
            if (this.page != 0)
                writer.writeInt32(14, this.page);
            if (this.pageSize != 0)
                writer.writeInt32(15, this.pageSize);
            if (this.version.length)
                writer.writeString(16, this.version);
            if (this.v != 0)
                writer.writeDouble(17, this.v);
            if (this.talkMode != 0)
                writer.writeInt32(18, this.talkMode);
            if (this.proto.length)
                writer.writeString(19, this.proto);
            if (this.nickname.length)
                writer.writeString(20, this.nickname);
            if (this.protocol.length)
                writer.writeBytes(21, this.protocol);
            if (this.deviceTag.length)
                writer.writeString(22, this.deviceTag);
            if (this.avatar.length)
                writer.writeString(23, this.avatar);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Meta {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Meta();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.deviceKey = reader.readString();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.userId = reader.readString();
                        break;
                    case 4:
                        message.roomId = reader.readInt64();
                        break;
                    case 5:
                        message.teamId = reader.readInt64();
                        break;
                    case 6:
                        message.startTime = reader.readString();
                        break;
                    case 7:
                        message.endTime = reader.readString();
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.token = reader.readString();
                        break;
                    case 10:
                        message.roomIds = reader.readPackedInt64();
                        break;
                    case 11:
                        pb_1.Message.addToRepeatedField(message, 11, reader.readString());
                        break;
                    case 12:
                        message.teamIds = reader.readPackedInt64();
                        break;
                    case 13:
                        message.keys = reader.readPackedInt64();
                        break;
                    case 14:
                        message.page = reader.readInt32();
                        break;
                    case 15:
                        message.pageSize = reader.readInt32();
                        break;
                    case 16:
                        message.version = reader.readString();
                        break;
                    case 17:
                        message.v = reader.readDouble();
                        break;
                    case 18:
                        message.talkMode = reader.readInt32();
                        break;
                    case 19:
                        message.proto = reader.readString();
                        break;
                    case 20:
                        message.nickname = reader.readString();
                        break;
                    case 21:
                        message.protocol = reader.readBytes();
                        break;
                    case 22:
                        message.deviceTag = reader.readString();
                        break;
                    case 23:
                        message.avatar = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Meta {
            return Meta.deserialize(bytes);
        }
    }
}
