/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Rooms.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as dependency_2 from "./Contacts";
import * as pb_1 from "google-protobuf";
export namespace onlyour.imio {
    export class Rooms extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.onlyour.imio.Meta;
            userId?: string;
            roomname?: string;
            level?: string;
            describe?: string;
            type?: string;
            joinKey?: string;
            talkMode?: number;
            userCount?: number;
            lurk?: number;
            depict?: string;
            muted?: number;
            applyJoin?: number;
            applyNeed?: number;
            invite?: number;
            uped?: number;
            downed?: number;
            revoke?: number;
            tags?: string[];
            users?: dependency_2.onlyour.imio.Contacts[];
            avatar?: string;
            groupToOne?: number;
            roomCount?: number;
            group?: number;
            teamCount?: number;
            ask?: string;
            answer?: string;
            roomIds?: string[];
            account?: string;
            roomMax?: number;
            teamMax?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8, 28, 29, 37], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("roomname" in data && data.roomname != undefined) {
                    this.roomname = data.roomname;
                }
                if ("level" in data && data.level != undefined) {
                    this.level = data.level;
                }
                if ("describe" in data && data.describe != undefined) {
                    this.describe = data.describe;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("joinKey" in data && data.joinKey != undefined) {
                    this.joinKey = data.joinKey;
                }
                if ("talkMode" in data && data.talkMode != undefined) {
                    this.talkMode = data.talkMode;
                }
                if ("userCount" in data && data.userCount != undefined) {
                    this.userCount = data.userCount;
                }
                if ("lurk" in data && data.lurk != undefined) {
                    this.lurk = data.lurk;
                }
                if ("depict" in data && data.depict != undefined) {
                    this.depict = data.depict;
                }
                if ("muted" in data && data.muted != undefined) {
                    this.muted = data.muted;
                }
                if ("applyJoin" in data && data.applyJoin != undefined) {
                    this.applyJoin = data.applyJoin;
                }
                if ("applyNeed" in data && data.applyNeed != undefined) {
                    this.applyNeed = data.applyNeed;
                }
                if ("invite" in data && data.invite != undefined) {
                    this.invite = data.invite;
                }
                if ("uped" in data && data.uped != undefined) {
                    this.uped = data.uped;
                }
                if ("downed" in data && data.downed != undefined) {
                    this.downed = data.downed;
                }
                if ("revoke" in data && data.revoke != undefined) {
                    this.revoke = data.revoke;
                }
                if ("tags" in data && data.tags != undefined) {
                    this.tags = data.tags;
                }
                if ("users" in data && data.users != undefined) {
                    this.users = data.users;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
                if ("groupToOne" in data && data.groupToOne != undefined) {
                    this.groupToOne = data.groupToOne;
                }
                if ("roomCount" in data && data.roomCount != undefined) {
                    this.roomCount = data.roomCount;
                }
                if ("group" in data && data.group != undefined) {
                    this.group = data.group;
                }
                if ("teamCount" in data && data.teamCount != undefined) {
                    this.teamCount = data.teamCount;
                }
                if ("ask" in data && data.ask != undefined) {
                    this.ask = data.ask;
                }
                if ("answer" in data && data.answer != undefined) {
                    this.answer = data.answer;
                }
                if ("roomIds" in data && data.roomIds != undefined) {
                    this.roomIds = data.roomIds;
                }
                if ("account" in data && data.account != undefined) {
                    this.account = data.account;
                }
                if ("roomMax" in data && data.roomMax != undefined) {
                    this.roomMax = data.roomMax;
                }
                if ("teamMax" in data && data.teamMax != undefined) {
                    this.teamMax = data.teamMax;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.onlyour.imio.Meta, 10) as dependency_1.onlyour.imio.Meta;
        }
        set meta(value: dependency_1.onlyour.imio.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get roomname() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set roomname(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get level() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set level(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get describe() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set describe(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get joinKey() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set joinKey(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get talkMode() {
            return pb_1.Message.getFieldWithDefault(this, 17, 0) as number;
        }
        set talkMode(value: number) {
            pb_1.Message.setField(this, 17, value);
        }
        get userCount() {
            return pb_1.Message.getFieldWithDefault(this, 18, 0) as number;
        }
        set userCount(value: number) {
            pb_1.Message.setField(this, 18, value);
        }
        get lurk() {
            return pb_1.Message.getFieldWithDefault(this, 19, 0) as number;
        }
        set lurk(value: number) {
            pb_1.Message.setField(this, 19, value);
        }
        get depict() {
            return pb_1.Message.getFieldWithDefault(this, 20, "") as string;
        }
        set depict(value: string) {
            pb_1.Message.setField(this, 20, value);
        }
        get muted() {
            return pb_1.Message.getFieldWithDefault(this, 21, 0) as number;
        }
        set muted(value: number) {
            pb_1.Message.setField(this, 21, value);
        }
        get applyJoin() {
            return pb_1.Message.getFieldWithDefault(this, 22, 0) as number;
        }
        set applyJoin(value: number) {
            pb_1.Message.setField(this, 22, value);
        }
        get applyNeed() {
            return pb_1.Message.getFieldWithDefault(this, 23, 0) as number;
        }
        set applyNeed(value: number) {
            pb_1.Message.setField(this, 23, value);
        }
        get invite() {
            return pb_1.Message.getFieldWithDefault(this, 24, 0) as number;
        }
        set invite(value: number) {
            pb_1.Message.setField(this, 24, value);
        }
        get uped() {
            return pb_1.Message.getFieldWithDefault(this, 25, 0) as number;
        }
        set uped(value: number) {
            pb_1.Message.setField(this, 25, value);
        }
        get downed() {
            return pb_1.Message.getFieldWithDefault(this, 26, 0) as number;
        }
        set downed(value: number) {
            pb_1.Message.setField(this, 26, value);
        }
        get revoke() {
            return pb_1.Message.getFieldWithDefault(this, 27, 0) as number;
        }
        set revoke(value: number) {
            pb_1.Message.setField(this, 27, value);
        }
        get tags() {
            return pb_1.Message.getFieldWithDefault(this, 28, []) as string[];
        }
        set tags(value: string[]) {
            pb_1.Message.setField(this, 28, value);
        }
        get users() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_2.onlyour.imio.Contacts, 29) as dependency_2.onlyour.imio.Contacts[];
        }
        set users(value: dependency_2.onlyour.imio.Contacts[]) {
            pb_1.Message.setRepeatedWrapperField(this, 29, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 30, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 30, value);
        }
        get groupToOne() {
            return pb_1.Message.getFieldWithDefault(this, 31, 0) as number;
        }
        set groupToOne(value: number) {
            pb_1.Message.setField(this, 31, value);
        }
        get roomCount() {
            return pb_1.Message.getFieldWithDefault(this, 32, 0) as number;
        }
        set roomCount(value: number) {
            pb_1.Message.setField(this, 32, value);
        }
        get group() {
            return pb_1.Message.getFieldWithDefault(this, 33, 0) as number;
        }
        set group(value: number) {
            pb_1.Message.setField(this, 33, value);
        }
        get teamCount() {
            return pb_1.Message.getFieldWithDefault(this, 34, 0) as number;
        }
        set teamCount(value: number) {
            pb_1.Message.setField(this, 34, value);
        }
        get ask() {
            return pb_1.Message.getFieldWithDefault(this, 35, "") as string;
        }
        set ask(value: string) {
            pb_1.Message.setField(this, 35, value);
        }
        get answer() {
            return pb_1.Message.getFieldWithDefault(this, 36, "") as string;
        }
        set answer(value: string) {
            pb_1.Message.setField(this, 36, value);
        }
        get roomIds() {
            return pb_1.Message.getFieldWithDefault(this, 37, []) as string[];
        }
        set roomIds(value: string[]) {
            pb_1.Message.setField(this, 37, value);
        }
        get account() {
            return pb_1.Message.getFieldWithDefault(this, 38, "") as string;
        }
        set account(value: string) {
            pb_1.Message.setField(this, 38, value);
        }
        get roomMax() {
            return pb_1.Message.getFieldWithDefault(this, 39, 0) as number;
        }
        set roomMax(value: number) {
            pb_1.Message.setField(this, 39, value);
        }
        get teamMax() {
            return pb_1.Message.getFieldWithDefault(this, 40, 0) as number;
        }
        set teamMax(value: number) {
            pb_1.Message.setField(this, 40, value);
        }
        static fromObject(data: {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
            userId?: string;
            roomname?: string;
            level?: string;
            describe?: string;
            type?: string;
            joinKey?: string;
            talkMode?: number;
            userCount?: number;
            lurk?: number;
            depict?: string;
            muted?: number;
            applyJoin?: number;
            applyNeed?: number;
            invite?: number;
            uped?: number;
            downed?: number;
            revoke?: number;
            tags?: string[];
            users?: ReturnType<typeof dependency_2.onlyour.imio.Contacts.prototype.toObject>[];
            avatar?: string;
            groupToOne?: number;
            roomCount?: number;
            group?: number;
            teamCount?: number;
            ask?: string;
            answer?: string;
            roomIds?: string[];
            account?: string;
            roomMax?: number;
            teamMax?: number;
        }): Rooms {
            const message = new Rooms({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.onlyour.imio.Meta.fromObject(data.meta);
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.roomname != null) {
                message.roomname = data.roomname;
            }
            if (data.level != null) {
                message.level = data.level;
            }
            if (data.describe != null) {
                message.describe = data.describe;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.joinKey != null) {
                message.joinKey = data.joinKey;
            }
            if (data.talkMode != null) {
                message.talkMode = data.talkMode;
            }
            if (data.userCount != null) {
                message.userCount = data.userCount;
            }
            if (data.lurk != null) {
                message.lurk = data.lurk;
            }
            if (data.depict != null) {
                message.depict = data.depict;
            }
            if (data.muted != null) {
                message.muted = data.muted;
            }
            if (data.applyJoin != null) {
                message.applyJoin = data.applyJoin;
            }
            if (data.applyNeed != null) {
                message.applyNeed = data.applyNeed;
            }
            if (data.invite != null) {
                message.invite = data.invite;
            }
            if (data.uped != null) {
                message.uped = data.uped;
            }
            if (data.downed != null) {
                message.downed = data.downed;
            }
            if (data.revoke != null) {
                message.revoke = data.revoke;
            }
            if (data.tags != null) {
                message.tags = data.tags;
            }
            if (data.users != null) {
                message.users = data.users.map(item => dependency_2.onlyour.imio.Contacts.fromObject(item));
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            if (data.groupToOne != null) {
                message.groupToOne = data.groupToOne;
            }
            if (data.roomCount != null) {
                message.roomCount = data.roomCount;
            }
            if (data.group != null) {
                message.group = data.group;
            }
            if (data.teamCount != null) {
                message.teamCount = data.teamCount;
            }
            if (data.ask != null) {
                message.ask = data.ask;
            }
            if (data.answer != null) {
                message.answer = data.answer;
            }
            if (data.roomIds != null) {
                message.roomIds = data.roomIds;
            }
            if (data.account != null) {
                message.account = data.account;
            }
            if (data.roomMax != null) {
                message.roomMax = data.roomMax;
            }
            if (data.teamMax != null) {
                message.teamMax = data.teamMax;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.onlyour.imio.Meta.prototype.toObject>;
                userId?: string;
                roomname?: string;
                level?: string;
                describe?: string;
                type?: string;
                joinKey?: string;
                talkMode?: number;
                userCount?: number;
                lurk?: number;
                depict?: string;
                muted?: number;
                applyJoin?: number;
                applyNeed?: number;
                invite?: number;
                uped?: number;
                downed?: number;
                revoke?: number;
                tags?: string[];
                users?: ReturnType<typeof dependency_2.onlyour.imio.Contacts.prototype.toObject>[];
                avatar?: string;
                groupToOne?: number;
                roomCount?: number;
                group?: number;
                teamCount?: number;
                ask?: string;
                answer?: string;
                roomIds?: string[];
                account?: string;
                roomMax?: number;
                teamMax?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.roomname != null) {
                data.roomname = this.roomname;
            }
            if (this.level != null) {
                data.level = this.level;
            }
            if (this.describe != null) {
                data.describe = this.describe;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.joinKey != null) {
                data.joinKey = this.joinKey;
            }
            if (this.talkMode != null) {
                data.talkMode = this.talkMode;
            }
            if (this.userCount != null) {
                data.userCount = this.userCount;
            }
            if (this.lurk != null) {
                data.lurk = this.lurk;
            }
            if (this.depict != null) {
                data.depict = this.depict;
            }
            if (this.muted != null) {
                data.muted = this.muted;
            }
            if (this.applyJoin != null) {
                data.applyJoin = this.applyJoin;
            }
            if (this.applyNeed != null) {
                data.applyNeed = this.applyNeed;
            }
            if (this.invite != null) {
                data.invite = this.invite;
            }
            if (this.uped != null) {
                data.uped = this.uped;
            }
            if (this.downed != null) {
                data.downed = this.downed;
            }
            if (this.revoke != null) {
                data.revoke = this.revoke;
            }
            if (this.tags != null) {
                data.tags = this.tags;
            }
            if (this.users != null) {
                data.users = this.users.map((item: dependency_2.onlyour.imio.Contacts) => item.toObject());
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            if (this.groupToOne != null) {
                data.groupToOne = this.groupToOne;
            }
            if (this.roomCount != null) {
                data.roomCount = this.roomCount;
            }
            if (this.group != null) {
                data.group = this.group;
            }
            if (this.teamCount != null) {
                data.teamCount = this.teamCount;
            }
            if (this.ask != null) {
                data.ask = this.ask;
            }
            if (this.answer != null) {
                data.answer = this.answer;
            }
            if (this.roomIds != null) {
                data.roomIds = this.roomIds;
            }
            if (this.account != null) {
                data.account = this.account;
            }
            if (this.roomMax != null) {
                data.roomMax = this.roomMax;
            }
            if (this.teamMax != null) {
                data.teamMax = this.teamMax;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.userId.length)
                writer.writeString(11, this.userId);
            if (this.roomname.length)
                writer.writeString(12, this.roomname);
            if (this.level.length)
                writer.writeString(13, this.level);
            if (this.describe.length)
                writer.writeString(14, this.describe);
            if (this.type.length)
                writer.writeString(15, this.type);
            if (this.joinKey.length)
                writer.writeString(16, this.joinKey);
            if (this.talkMode != 0)
                writer.writeInt32(17, this.talkMode);
            if (this.userCount != 0)
                writer.writeInt32(18, this.userCount);
            if (this.lurk != 0)
                writer.writeInt32(19, this.lurk);
            if (this.depict.length)
                writer.writeString(20, this.depict);
            if (this.muted != 0)
                writer.writeInt32(21, this.muted);
            if (this.applyJoin != 0)
                writer.writeInt32(22, this.applyJoin);
            if (this.applyNeed != 0)
                writer.writeInt32(23, this.applyNeed);
            if (this.invite != 0)
                writer.writeInt32(24, this.invite);
            if (this.uped != 0)
                writer.writeInt32(25, this.uped);
            if (this.downed != 0)
                writer.writeInt32(26, this.downed);
            if (this.revoke != 0)
                writer.writeInt32(27, this.revoke);
            if (this.tags.length)
                writer.writeRepeatedString(28, this.tags);
            if (this.users.length)
                writer.writeRepeatedMessage(29, this.users, (item: dependency_2.onlyour.imio.Contacts) => item.serialize(writer));
            if (this.avatar.length)
                writer.writeString(30, this.avatar);
            if (this.groupToOne != 0)
                writer.writeInt32(31, this.groupToOne);
            if (this.roomCount != 0)
                writer.writeInt32(32, this.roomCount);
            if (this.group != 0)
                writer.writeInt32(33, this.group);
            if (this.teamCount != 0)
                writer.writeInt32(34, this.teamCount);
            if (this.ask.length)
                writer.writeString(35, this.ask);
            if (this.answer.length)
                writer.writeString(36, this.answer);
            if (this.roomIds.length)
                writer.writeRepeatedString(37, this.roomIds);
            if (this.account.length)
                writer.writeString(38, this.account);
            if (this.roomMax != 0)
                writer.writeInt32(39, this.roomMax);
            if (this.teamMax != 0)
                writer.writeInt32(40, this.teamMax);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Rooms {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Rooms();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.onlyour.imio.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.userId = reader.readString();
                        break;
                    case 12:
                        message.roomname = reader.readString();
                        break;
                    case 13:
                        message.level = reader.readString();
                        break;
                    case 14:
                        message.describe = reader.readString();
                        break;
                    case 15:
                        message.type = reader.readString();
                        break;
                    case 16:
                        message.joinKey = reader.readString();
                        break;
                    case 17:
                        message.talkMode = reader.readInt32();
                        break;
                    case 18:
                        message.userCount = reader.readInt32();
                        break;
                    case 19:
                        message.lurk = reader.readInt32();
                        break;
                    case 20:
                        message.depict = reader.readString();
                        break;
                    case 21:
                        message.muted = reader.readInt32();
                        break;
                    case 22:
                        message.applyJoin = reader.readInt32();
                        break;
                    case 23:
                        message.applyNeed = reader.readInt32();
                        break;
                    case 24:
                        message.invite = reader.readInt32();
                        break;
                    case 25:
                        message.uped = reader.readInt32();
                        break;
                    case 26:
                        message.downed = reader.readInt32();
                        break;
                    case 27:
                        message.revoke = reader.readInt32();
                        break;
                    case 28:
                        pb_1.Message.addToRepeatedField(message, 28, reader.readString());
                        break;
                    case 29:
                        reader.readMessage(message.users, () => pb_1.Message.addToRepeatedWrapperField(message, 29, dependency_2.onlyour.imio.Contacts.deserialize(reader), dependency_2.onlyour.imio.Contacts));
                        break;
                    case 30:
                        message.avatar = reader.readString();
                        break;
                    case 31:
                        message.groupToOne = reader.readInt32();
                        break;
                    case 32:
                        message.roomCount = reader.readInt32();
                        break;
                    case 33:
                        message.group = reader.readInt32();
                        break;
                    case 34:
                        message.teamCount = reader.readInt32();
                        break;
                    case 35:
                        message.ask = reader.readString();
                        break;
                    case 36:
                        message.answer = reader.readString();
                        break;
                    case 37:
                        pb_1.Message.addToRepeatedField(message, 37, reader.readString());
                        break;
                    case 38:
                        message.account = reader.readString();
                        break;
                    case 39:
                        message.roomMax = reader.readInt32();
                        break;
                    case 40:
                        message.teamMax = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Rooms {
            return Rooms.deserialize(bytes);
        }
    }
}
