/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: TeamContact.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as pb_1 from "google-protobuf";
export namespace only {
    export class TeamContact extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.only.Meta;
            userId?: string;
            account?: string;
            nickname?: string;
            username?: string;
            avatar?: string;
            role?: string;
            deviceKey?: string;
            muted?: number;
            deviceTag?: string;
            roomId?: number;
            black?: number;
            talkMode?: number;
            teamname?: string;
            noise?: number;
            topic?: string;
            joinTeamId?: number;
            fromTeamId?: number;
            teamIds?: number[];
            userIds?: number[];
            joinTime?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8, 28, 29], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("account" in data && data.account != undefined) {
                    this.account = data.account;
                }
                if ("nickname" in data && data.nickname != undefined) {
                    this.nickname = data.nickname;
                }
                if ("username" in data && data.username != undefined) {
                    this.username = data.username;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
                if ("role" in data && data.role != undefined) {
                    this.role = data.role;
                }
                if ("deviceKey" in data && data.deviceKey != undefined) {
                    this.deviceKey = data.deviceKey;
                }
                if ("muted" in data && data.muted != undefined) {
                    this.muted = data.muted;
                }
                if ("deviceTag" in data && data.deviceTag != undefined) {
                    this.deviceTag = data.deviceTag;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("black" in data && data.black != undefined) {
                    this.black = data.black;
                }
                if ("talkMode" in data && data.talkMode != undefined) {
                    this.talkMode = data.talkMode;
                }
                if ("teamname" in data && data.teamname != undefined) {
                    this.teamname = data.teamname;
                }
                if ("noise" in data && data.noise != undefined) {
                    this.noise = data.noise;
                }
                if ("topic" in data && data.topic != undefined) {
                    this.topic = data.topic;
                }
                if ("joinTeamId" in data && data.joinTeamId != undefined) {
                    this.joinTeamId = data.joinTeamId;
                }
                if ("fromTeamId" in data && data.fromTeamId != undefined) {
                    this.fromTeamId = data.fromTeamId;
                }
                if ("teamIds" in data && data.teamIds != undefined) {
                    this.teamIds = data.teamIds;
                }
                if ("userIds" in data && data.userIds != undefined) {
                    this.userIds = data.userIds;
                }
                if ("joinTime" in data && data.joinTime != undefined) {
                    this.joinTime = data.joinTime;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.only.Meta, 10) as dependency_1.only.Meta;
        }
        set meta(value: dependency_1.only.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get account() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set account(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get nickname() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set nickname(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get username() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set username(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get role() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set role(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get deviceKey() {
            return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
        }
        set deviceKey(value: string) {
            pb_1.Message.setField(this, 17, value);
        }
        get muted() {
            return pb_1.Message.getFieldWithDefault(this, 18, 0) as number;
        }
        set muted(value: number) {
            pb_1.Message.setField(this, 18, value);
        }
        get deviceTag() {
            return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
        }
        set deviceTag(value: string) {
            pb_1.Message.setField(this, 19, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 20, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 20, value);
        }
        get black() {
            return pb_1.Message.getFieldWithDefault(this, 21, 0) as number;
        }
        set black(value: number) {
            pb_1.Message.setField(this, 21, value);
        }
        get talkMode() {
            return pb_1.Message.getFieldWithDefault(this, 22, 0) as number;
        }
        set talkMode(value: number) {
            pb_1.Message.setField(this, 22, value);
        }
        get teamname() {
            return pb_1.Message.getFieldWithDefault(this, 23, "") as string;
        }
        set teamname(value: string) {
            pb_1.Message.setField(this, 23, value);
        }
        get noise() {
            return pb_1.Message.getFieldWithDefault(this, 24, 0) as number;
        }
        set noise(value: number) {
            pb_1.Message.setField(this, 24, value);
        }
        get topic() {
            return pb_1.Message.getFieldWithDefault(this, 25, "") as string;
        }
        set topic(value: string) {
            pb_1.Message.setField(this, 25, value);
        }
        get joinTeamId() {
            return pb_1.Message.getFieldWithDefault(this, 26, 0) as number;
        }
        set joinTeamId(value: number) {
            pb_1.Message.setField(this, 26, value);
        }
        get fromTeamId() {
            return pb_1.Message.getFieldWithDefault(this, 27, 0) as number;
        }
        set fromTeamId(value: number) {
            pb_1.Message.setField(this, 27, value);
        }
        get teamIds() {
            return pb_1.Message.getFieldWithDefault(this, 28, []) as number[];
        }
        set teamIds(value: number[]) {
            pb_1.Message.setField(this, 28, value);
        }
        get userIds() {
            return pb_1.Message.getFieldWithDefault(this, 29, []) as number[];
        }
        set userIds(value: number[]) {
            pb_1.Message.setField(this, 29, value);
        }
        get joinTime() {
            return pb_1.Message.getFieldWithDefault(this, 30, "") as string;
        }
        set joinTime(value: string) {
            pb_1.Message.setField(this, 30, value);
        }
        static fromObject(data: {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
            userId?: string;
            account?: string;
            nickname?: string;
            username?: string;
            avatar?: string;
            role?: string;
            deviceKey?: string;
            muted?: number;
            deviceTag?: string;
            roomId?: number;
            black?: number;
            talkMode?: number;
            teamname?: string;
            noise?: number;
            topic?: string;
            joinTeamId?: number;
            fromTeamId?: number;
            teamIds?: number[];
            userIds?: number[];
            joinTime?: string;
        }): TeamContact {
            const message = new TeamContact({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.only.Meta.fromObject(data.meta);
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.account != null) {
                message.account = data.account;
            }
            if (data.nickname != null) {
                message.nickname = data.nickname;
            }
            if (data.username != null) {
                message.username = data.username;
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            if (data.role != null) {
                message.role = data.role;
            }
            if (data.deviceKey != null) {
                message.deviceKey = data.deviceKey;
            }
            if (data.muted != null) {
                message.muted = data.muted;
            }
            if (data.deviceTag != null) {
                message.deviceTag = data.deviceTag;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.black != null) {
                message.black = data.black;
            }
            if (data.talkMode != null) {
                message.talkMode = data.talkMode;
            }
            if (data.teamname != null) {
                message.teamname = data.teamname;
            }
            if (data.noise != null) {
                message.noise = data.noise;
            }
            if (data.topic != null) {
                message.topic = data.topic;
            }
            if (data.joinTeamId != null) {
                message.joinTeamId = data.joinTeamId;
            }
            if (data.fromTeamId != null) {
                message.fromTeamId = data.fromTeamId;
            }
            if (data.teamIds != null) {
                message.teamIds = data.teamIds;
            }
            if (data.userIds != null) {
                message.userIds = data.userIds;
            }
            if (data.joinTime != null) {
                message.joinTime = data.joinTime;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
                userId?: string;
                account?: string;
                nickname?: string;
                username?: string;
                avatar?: string;
                role?: string;
                deviceKey?: string;
                muted?: number;
                deviceTag?: string;
                roomId?: number;
                black?: number;
                talkMode?: number;
                teamname?: string;
                noise?: number;
                topic?: string;
                joinTeamId?: number;
                fromTeamId?: number;
                teamIds?: number[];
                userIds?: number[];
                joinTime?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.account != null) {
                data.account = this.account;
            }
            if (this.nickname != null) {
                data.nickname = this.nickname;
            }
            if (this.username != null) {
                data.username = this.username;
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            if (this.role != null) {
                data.role = this.role;
            }
            if (this.deviceKey != null) {
                data.deviceKey = this.deviceKey;
            }
            if (this.muted != null) {
                data.muted = this.muted;
            }
            if (this.deviceTag != null) {
                data.deviceTag = this.deviceTag;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.black != null) {
                data.black = this.black;
            }
            if (this.talkMode != null) {
                data.talkMode = this.talkMode;
            }
            if (this.teamname != null) {
                data.teamname = this.teamname;
            }
            if (this.noise != null) {
                data.noise = this.noise;
            }
            if (this.topic != null) {
                data.topic = this.topic;
            }
            if (this.joinTeamId != null) {
                data.joinTeamId = this.joinTeamId;
            }
            if (this.fromTeamId != null) {
                data.fromTeamId = this.fromTeamId;
            }
            if (this.teamIds != null) {
                data.teamIds = this.teamIds;
            }
            if (this.userIds != null) {
                data.userIds = this.userIds;
            }
            if (this.joinTime != null) {
                data.joinTime = this.joinTime;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.userId.length)
                writer.writeString(11, this.userId);
            if (this.account.length)
                writer.writeString(12, this.account);
            if (this.nickname.length)
                writer.writeString(13, this.nickname);
            if (this.username.length)
                writer.writeString(14, this.username);
            if (this.avatar.length)
                writer.writeString(15, this.avatar);
            if (this.role.length)
                writer.writeString(16, this.role);
            if (this.deviceKey.length)
                writer.writeString(17, this.deviceKey);
            if (this.muted != 0)
                writer.writeInt32(18, this.muted);
            if (this.deviceTag.length)
                writer.writeString(19, this.deviceTag);
            if (this.roomId != 0)
                writer.writeInt64(20, this.roomId);
            if (this.black != 0)
                writer.writeInt32(21, this.black);
            if (this.talkMode != 0)
                writer.writeInt32(22, this.talkMode);
            if (this.teamname.length)
                writer.writeString(23, this.teamname);
            if (this.noise != 0)
                writer.writeInt32(24, this.noise);
            if (this.topic.length)
                writer.writeString(25, this.topic);
            if (this.joinTeamId != 0)
                writer.writeInt64(26, this.joinTeamId);
            if (this.fromTeamId != 0)
                writer.writeInt64(27, this.fromTeamId);
            if (this.teamIds.length)
                writer.writePackedInt64(28, this.teamIds);
            if (this.userIds.length)
                writer.writePackedInt64(29, this.userIds);
            if (this.joinTime.length)
                writer.writeString(30, this.joinTime);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TeamContact {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TeamContact();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.only.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.userId = reader.readString();
                        break;
                    case 12:
                        message.account = reader.readString();
                        break;
                    case 13:
                        message.nickname = reader.readString();
                        break;
                    case 14:
                        message.username = reader.readString();
                        break;
                    case 15:
                        message.avatar = reader.readString();
                        break;
                    case 16:
                        message.role = reader.readString();
                        break;
                    case 17:
                        message.deviceKey = reader.readString();
                        break;
                    case 18:
                        message.muted = reader.readInt32();
                        break;
                    case 19:
                        message.deviceTag = reader.readString();
                        break;
                    case 20:
                        message.roomId = reader.readInt64();
                        break;
                    case 21:
                        message.black = reader.readInt32();
                        break;
                    case 22:
                        message.talkMode = reader.readInt32();
                        break;
                    case 23:
                        message.teamname = reader.readString();
                        break;
                    case 24:
                        message.noise = reader.readInt32();
                        break;
                    case 25:
                        message.topic = reader.readString();
                        break;
                    case 26:
                        message.joinTeamId = reader.readInt64();
                        break;
                    case 27:
                        message.fromTeamId = reader.readInt64();
                        break;
                    case 28:
                        message.teamIds = reader.readPackedInt64();
                        break;
                    case 29:
                        message.userIds = reader.readPackedInt64();
                        break;
                    case 30:
                        message.joinTime = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TeamContact {
            return TeamContact.deserialize(bytes);
        }
    }
}
