/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Teams.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as dependency_2 from "./TeamContact";
import * as pb_1 from "google-protobuf";
export namespace only {
    export class Teams extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.only.Meta;
            userId?: string;
            teamname?: string;
            roomId?: number;
            account?: string;
            deviceTag?: string;
            noise?: number;
            deviceKey?: string;
            muted?: number;
            teamMax?: number;
            revoke?: number;
            member?: dependency_2.only.TeamContact[];
            avatar?: string;
            talkMode?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8, 24], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("teamname" in data && data.teamname != undefined) {
                    this.teamname = data.teamname;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("account" in data && data.account != undefined) {
                    this.account = data.account;
                }
                if ("deviceTag" in data && data.deviceTag != undefined) {
                    this.deviceTag = data.deviceTag;
                }
                if ("noise" in data && data.noise != undefined) {
                    this.noise = data.noise;
                }
                if ("deviceKey" in data && data.deviceKey != undefined) {
                    this.deviceKey = data.deviceKey;
                }
                if ("muted" in data && data.muted != undefined) {
                    this.muted = data.muted;
                }
                if ("teamMax" in data && data.teamMax != undefined) {
                    this.teamMax = data.teamMax;
                }
                if ("revoke" in data && data.revoke != undefined) {
                    this.revoke = data.revoke;
                }
                if ("member" in data && data.member != undefined) {
                    this.member = data.member;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
                if ("talkMode" in data && data.talkMode != undefined) {
                    this.talkMode = data.talkMode;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.only.Meta, 10) as dependency_1.only.Meta;
        }
        set meta(value: dependency_1.only.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get teamname() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set teamname(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 13, value);
        }
        get account() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set account(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get deviceTag() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set deviceTag(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get noise() {
            return pb_1.Message.getFieldWithDefault(this, 19, 0) as number;
        }
        set noise(value: number) {
            pb_1.Message.setField(this, 19, value);
        }
        get deviceKey() {
            return pb_1.Message.getFieldWithDefault(this, 20, "") as string;
        }
        set deviceKey(value: string) {
            pb_1.Message.setField(this, 20, value);
        }
        get muted() {
            return pb_1.Message.getFieldWithDefault(this, 21, 0) as number;
        }
        set muted(value: number) {
            pb_1.Message.setField(this, 21, value);
        }
        get teamMax() {
            return pb_1.Message.getFieldWithDefault(this, 22, 0) as number;
        }
        set teamMax(value: number) {
            pb_1.Message.setField(this, 22, value);
        }
        get revoke() {
            return pb_1.Message.getFieldWithDefault(this, 23, 0) as number;
        }
        set revoke(value: number) {
            pb_1.Message.setField(this, 23, value);
        }
        get member() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_2.only.TeamContact, 24) as dependency_2.only.TeamContact[];
        }
        set member(value: dependency_2.only.TeamContact[]) {
            pb_1.Message.setRepeatedWrapperField(this, 24, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 25, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 25, value);
        }
        get talkMode() {
            return pb_1.Message.getFieldWithDefault(this, 26, 0) as number;
        }
        set talkMode(value: number) {
            pb_1.Message.setField(this, 26, value);
        }
        static fromObject(data: {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
            userId?: string;
            teamname?: string;
            roomId?: number;
            account?: string;
            deviceTag?: string;
            noise?: number;
            deviceKey?: string;
            muted?: number;
            teamMax?: number;
            revoke?: number;
            member?: ReturnType<typeof dependency_2.only.TeamContact.prototype.toObject>[];
            avatar?: string;
            talkMode?: number;
        }): Teams {
            const message = new Teams({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.only.Meta.fromObject(data.meta);
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.teamname != null) {
                message.teamname = data.teamname;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.account != null) {
                message.account = data.account;
            }
            if (data.deviceTag != null) {
                message.deviceTag = data.deviceTag;
            }
            if (data.noise != null) {
                message.noise = data.noise;
            }
            if (data.deviceKey != null) {
                message.deviceKey = data.deviceKey;
            }
            if (data.muted != null) {
                message.muted = data.muted;
            }
            if (data.teamMax != null) {
                message.teamMax = data.teamMax;
            }
            if (data.revoke != null) {
                message.revoke = data.revoke;
            }
            if (data.member != null) {
                message.member = data.member.map(item => dependency_2.only.TeamContact.fromObject(item));
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            if (data.talkMode != null) {
                message.talkMode = data.talkMode;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
                userId?: string;
                teamname?: string;
                roomId?: number;
                account?: string;
                deviceTag?: string;
                noise?: number;
                deviceKey?: string;
                muted?: number;
                teamMax?: number;
                revoke?: number;
                member?: ReturnType<typeof dependency_2.only.TeamContact.prototype.toObject>[];
                avatar?: string;
                talkMode?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.teamname != null) {
                data.teamname = this.teamname;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.account != null) {
                data.account = this.account;
            }
            if (this.deviceTag != null) {
                data.deviceTag = this.deviceTag;
            }
            if (this.noise != null) {
                data.noise = this.noise;
            }
            if (this.deviceKey != null) {
                data.deviceKey = this.deviceKey;
            }
            if (this.muted != null) {
                data.muted = this.muted;
            }
            if (this.teamMax != null) {
                data.teamMax = this.teamMax;
            }
            if (this.revoke != null) {
                data.revoke = this.revoke;
            }
            if (this.member != null) {
                data.member = this.member.map((item: dependency_2.only.TeamContact) => item.toObject());
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            if (this.talkMode != null) {
                data.talkMode = this.talkMode;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.userId.length)
                writer.writeString(11, this.userId);
            if (this.teamname.length)
                writer.writeString(12, this.teamname);
            if (this.roomId != 0)
                writer.writeInt64(13, this.roomId);
            if (this.account.length)
                writer.writeString(14, this.account);
            if (this.deviceTag.length)
                writer.writeString(16, this.deviceTag);
            if (this.noise != 0)
                writer.writeInt32(19, this.noise);
            if (this.deviceKey.length)
                writer.writeString(20, this.deviceKey);
            if (this.muted != 0)
                writer.writeInt32(21, this.muted);
            if (this.teamMax != 0)
                writer.writeInt32(22, this.teamMax);
            if (this.revoke != 0)
                writer.writeInt32(23, this.revoke);
            if (this.member.length)
                writer.writeRepeatedMessage(24, this.member, (item: dependency_2.only.TeamContact) => item.serialize(writer));
            if (this.avatar.length)
                writer.writeString(25, this.avatar);
            if (this.talkMode != 0)
                writer.writeInt32(26, this.talkMode);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Teams {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Teams();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.only.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.userId = reader.readString();
                        break;
                    case 12:
                        message.teamname = reader.readString();
                        break;
                    case 13:
                        message.roomId = reader.readInt64();
                        break;
                    case 14:
                        message.account = reader.readString();
                        break;
                    case 16:
                        message.deviceTag = reader.readString();
                        break;
                    case 19:
                        message.noise = reader.readInt32();
                        break;
                    case 20:
                        message.deviceKey = reader.readString();
                        break;
                    case 21:
                        message.muted = reader.readInt32();
                        break;
                    case 22:
                        message.teamMax = reader.readInt32();
                        break;
                    case 23:
                        message.revoke = reader.readInt32();
                        break;
                    case 24:
                        reader.readMessage(message.member, () => pb_1.Message.addToRepeatedWrapperField(message, 24, dependency_2.only.TeamContact.deserialize(reader), dependency_2.only.TeamContact));
                        break;
                    case 25:
                        message.avatar = reader.readString();
                        break;
                    case 26:
                        message.talkMode = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Teams {
            return Teams.deserialize(bytes);
        }
    }
}
