/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: UserStatus.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as pb_1 from "google-protobuf";
export namespace only {
    export class UserStatus extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.only.Meta;
            userId?: string;
            device?: string;
            roomId?: number;
            status?: string;
            state?: string;
            gateway?: string;
            deviceKey?: string;
            deviceTag?: string;
            region?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("device" in data && data.device != undefined) {
                    this.device = data.device;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("state" in data && data.state != undefined) {
                    this.state = data.state;
                }
                if ("gateway" in data && data.gateway != undefined) {
                    this.gateway = data.gateway;
                }
                if ("deviceKey" in data && data.deviceKey != undefined) {
                    this.deviceKey = data.deviceKey;
                }
                if ("deviceTag" in data && data.deviceTag != undefined) {
                    this.deviceTag = data.deviceTag;
                }
                if ("region" in data && data.region != undefined) {
                    this.region = data.region;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.only.Meta, 10) as dependency_1.only.Meta;
        }
        set meta(value: dependency_1.only.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get device() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set device(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 13, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 13, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set status(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get state() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set state(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get gateway() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set gateway(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get deviceKey() {
            return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
        }
        set deviceKey(value: string) {
            pb_1.Message.setField(this, 17, value);
        }
        get deviceTag() {
            return pb_1.Message.getFieldWithDefault(this, 18, "") as string;
        }
        set deviceTag(value: string) {
            pb_1.Message.setField(this, 18, value);
        }
        get region() {
            return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
        }
        set region(value: string) {
            pb_1.Message.setField(this, 19, value);
        }
        static fromObject(data: {
            id?: number;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
            userId?: string;
            device?: string;
            roomId?: number;
            status?: string;
            state?: string;
            gateway?: string;
            deviceKey?: string;
            deviceTag?: string;
            region?: string;
        }): UserStatus {
            const message = new UserStatus({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.only.Meta.fromObject(data.meta);
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.device != null) {
                message.device = data.device;
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.state != null) {
                message.state = data.state;
            }
            if (data.gateway != null) {
                message.gateway = data.gateway;
            }
            if (data.deviceKey != null) {
                message.deviceKey = data.deviceKey;
            }
            if (data.deviceTag != null) {
                message.deviceTag = data.deviceTag;
            }
            if (data.region != null) {
                message.region = data.region;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
                userId?: string;
                device?: string;
                roomId?: number;
                status?: string;
                state?: string;
                gateway?: string;
                deviceKey?: string;
                deviceTag?: string;
                region?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.device != null) {
                data.device = this.device;
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.state != null) {
                data.state = this.state;
            }
            if (this.gateway != null) {
                data.gateway = this.gateway;
            }
            if (this.deviceKey != null) {
                data.deviceKey = this.deviceKey;
            }
            if (this.deviceTag != null) {
                data.deviceTag = this.deviceTag;
            }
            if (this.region != null) {
                data.region = this.region;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.userId.length)
                writer.writeString(11, this.userId);
            if (this.device.length)
                writer.writeString(12, this.device);
            if (this.roomId != 0)
                writer.writeInt64(13, this.roomId);
            if (this.status.length)
                writer.writeString(14, this.status);
            if (this.state.length)
                writer.writeString(15, this.state);
            if (this.gateway.length)
                writer.writeString(16, this.gateway);
            if (this.deviceKey.length)
                writer.writeString(17, this.deviceKey);
            if (this.deviceTag.length)
                writer.writeString(18, this.deviceTag);
            if (this.region.length)
                writer.writeString(19, this.region);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserStatus {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserStatus();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.only.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.userId = reader.readString();
                        break;
                    case 12:
                        message.device = reader.readString();
                        break;
                    case 13:
                        message.roomId = reader.readInt64();
                        break;
                    case 14:
                        message.status = reader.readString();
                        break;
                    case 15:
                        message.state = reader.readString();
                        break;
                    case 16:
                        message.gateway = reader.readString();
                        break;
                    case 17:
                        message.deviceKey = reader.readString();
                        break;
                    case 18:
                        message.deviceTag = reader.readString();
                        break;
                    case 19:
                        message.region = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UserStatus {
            return UserStatus.deserialize(bytes);
        }
    }
}
