/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: Users.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Meta";
import * as pb_1 from "google-protobuf";
export namespace only {
    export class Users extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: dependency_1.only.Meta;
            roomId?: number;
            nickname?: string;
            username?: string;
            account?: string;
            mobile?: string;
            email?: string;
            avatar?: string;
            gender?: number;
            birth?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("appId" in data && data.appId != undefined) {
                    this.appId = data.appId;
                }
                if ("v" in data && data.v != undefined) {
                    this.v = data.v;
                }
                if ("sort" in data && data.sort != undefined) {
                    this.sort = data.sort;
                }
                if ("created" in data && data.created != undefined) {
                    this.created = data.created;
                }
                if ("modified" in data && data.modified != undefined) {
                    this.modified = data.modified;
                }
                if ("ids" in data && data.ids != undefined) {
                    this.ids = data.ids;
                }
                if ("appIds" in data && data.appIds != undefined) {
                    this.appIds = data.appIds;
                }
                if ("remark" in data && data.remark != undefined) {
                    this.remark = data.remark;
                }
                if ("meta" in data && data.meta != undefined) {
                    this.meta = data.meta;
                }
                if ("roomId" in data && data.roomId != undefined) {
                    this.roomId = data.roomId;
                }
                if ("nickname" in data && data.nickname != undefined) {
                    this.nickname = data.nickname;
                }
                if ("username" in data && data.username != undefined) {
                    this.username = data.username;
                }
                if ("account" in data && data.account != undefined) {
                    this.account = data.account;
                }
                if ("mobile" in data && data.mobile != undefined) {
                    this.mobile = data.mobile;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
                if ("gender" in data && data.gender != undefined) {
                    this.gender = data.gender;
                }
                if ("birth" in data && data.birth != undefined) {
                    this.birth = data.birth;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get appId() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set appId(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get v() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set v(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get sort() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set sort(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get created() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set created(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get modified() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set modified(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get ids() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set ids(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get appIds() {
            return pb_1.Message.getFieldWithDefault(this, 8, []) as string[];
        }
        set appIds(value: string[]) {
            pb_1.Message.setField(this, 8, value);
        }
        get remark() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set remark(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get meta() {
            return pb_1.Message.getWrapperField(this, dependency_1.only.Meta, 10) as dependency_1.only.Meta;
        }
        set meta(value: dependency_1.only.Meta) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_meta() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get roomId() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set roomId(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get nickname() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set nickname(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get username() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set username(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get account() {
            return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
        }
        set account(value: string) {
            pb_1.Message.setField(this, 14, value);
        }
        get mobile() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set mobile(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 16, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 17, value);
        }
        get gender() {
            return pb_1.Message.getFieldWithDefault(this, 18, 0) as number;
        }
        set gender(value: number) {
            pb_1.Message.setField(this, 18, value);
        }
        get birth() {
            return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
        }
        set birth(value: string) {
            pb_1.Message.setField(this, 19, value);
        }
        static fromObject(data: {
            id?: string;
            appId?: number;
            v?: number;
            sort?: number;
            created?: string;
            modified?: string;
            ids?: string[];
            appIds?: string[];
            remark?: string;
            meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
            roomId?: number;
            nickname?: string;
            username?: string;
            account?: string;
            mobile?: string;
            email?: string;
            avatar?: string;
            gender?: number;
            birth?: string;
        }): Users {
            const message = new Users({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.appId != null) {
                message.appId = data.appId;
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.sort != null) {
                message.sort = data.sort;
            }
            if (data.created != null) {
                message.created = data.created;
            }
            if (data.modified != null) {
                message.modified = data.modified;
            }
            if (data.ids != null) {
                message.ids = data.ids;
            }
            if (data.appIds != null) {
                message.appIds = data.appIds;
            }
            if (data.remark != null) {
                message.remark = data.remark;
            }
            if (data.meta != null) {
                message.meta = dependency_1.only.Meta.fromObject(data.meta);
            }
            if (data.roomId != null) {
                message.roomId = data.roomId;
            }
            if (data.nickname != null) {
                message.nickname = data.nickname;
            }
            if (data.username != null) {
                message.username = data.username;
            }
            if (data.account != null) {
                message.account = data.account;
            }
            if (data.mobile != null) {
                message.mobile = data.mobile;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            if (data.gender != null) {
                message.gender = data.gender;
            }
            if (data.birth != null) {
                message.birth = data.birth;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                appId?: number;
                v?: number;
                sort?: number;
                created?: string;
                modified?: string;
                ids?: string[];
                appIds?: string[];
                remark?: string;
                meta?: ReturnType<typeof dependency_1.only.Meta.prototype.toObject>;
                roomId?: number;
                nickname?: string;
                username?: string;
                account?: string;
                mobile?: string;
                email?: string;
                avatar?: string;
                gender?: number;
                birth?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.appId != null) {
                data.appId = this.appId;
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.sort != null) {
                data.sort = this.sort;
            }
            if (this.created != null) {
                data.created = this.created;
            }
            if (this.modified != null) {
                data.modified = this.modified;
            }
            if (this.ids != null) {
                data.ids = this.ids;
            }
            if (this.appIds != null) {
                data.appIds = this.appIds;
            }
            if (this.remark != null) {
                data.remark = this.remark;
            }
            if (this.meta != null) {
                data.meta = this.meta.toObject();
            }
            if (this.roomId != null) {
                data.roomId = this.roomId;
            }
            if (this.nickname != null) {
                data.nickname = this.nickname;
            }
            if (this.username != null) {
                data.username = this.username;
            }
            if (this.account != null) {
                data.account = this.account;
            }
            if (this.mobile != null) {
                data.mobile = this.mobile;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            if (this.gender != null) {
                data.gender = this.gender;
            }
            if (this.birth != null) {
                data.birth = this.birth;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.appId != 0)
                writer.writeInt64(2, this.appId);
            if (this.v != 0)
                writer.writeDouble(3, this.v);
            if (this.sort != 0)
                writer.writeInt32(4, this.sort);
            if (this.created.length)
                writer.writeString(5, this.created);
            if (this.modified.length)
                writer.writeString(6, this.modified);
            if (this.ids.length)
                writer.writeRepeatedString(7, this.ids);
            if (this.appIds.length)
                writer.writeRepeatedString(8, this.appIds);
            if (this.remark.length)
                writer.writeString(9, this.remark);
            if (this.has_meta)
                writer.writeMessage(10, this.meta, () => this.meta.serialize(writer));
            if (this.roomId != 0)
                writer.writeInt64(11, this.roomId);
            if (this.nickname.length)
                writer.writeString(12, this.nickname);
            if (this.username.length)
                writer.writeString(13, this.username);
            if (this.account.length)
                writer.writeString(14, this.account);
            if (this.mobile.length)
                writer.writeString(15, this.mobile);
            if (this.email.length)
                writer.writeString(16, this.email);
            if (this.avatar.length)
                writer.writeString(17, this.avatar);
            if (this.gender != 0)
                writer.writeInt32(18, this.gender);
            if (this.birth.length)
                writer.writeString(19, this.birth);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Users {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Users();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.appId = reader.readInt64();
                        break;
                    case 3:
                        message.v = reader.readDouble();
                        break;
                    case 4:
                        message.sort = reader.readInt32();
                        break;
                    case 5:
                        message.created = reader.readString();
                        break;
                    case 6:
                        message.modified = reader.readString();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 8:
                        pb_1.Message.addToRepeatedField(message, 8, reader.readString());
                        break;
                    case 9:
                        message.remark = reader.readString();
                        break;
                    case 10:
                        reader.readMessage(message.meta, () => message.meta = dependency_1.only.Meta.deserialize(reader));
                        break;
                    case 11:
                        message.roomId = reader.readInt64();
                        break;
                    case 12:
                        message.nickname = reader.readString();
                        break;
                    case 13:
                        message.username = reader.readString();
                        break;
                    case 14:
                        message.account = reader.readString();
                        break;
                    case 15:
                        message.mobile = reader.readString();
                        break;
                    case 16:
                        message.email = reader.readString();
                        break;
                    case 17:
                        message.avatar = reader.readString();
                        break;
                    case 18:
                        message.gender = reader.readInt32();
                        break;
                    case 19:
                        message.birth = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Users {
            return Users.deserialize(bytes);
        }
    }
}
